// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_V_9_reload,
        buf_V_8_reload,
        buf_V_7_reload,
        buf_V_6_reload,
        buf_V_5_reload,
        buf_V_4_reload,
        buf_V_3_reload,
        buf_V_2_reload,
        buf_V_1_reload,
        buf_V_reload,
        inputs_address0,
        inputs_ce0,
        inputs_q0,
        lhs_18_out,
        lhs_18_out_ap_vld,
        lhs_16_out,
        lhs_16_out_ap_vld,
        lhs_14_out,
        lhs_14_out_ap_vld,
        lhs_12_out,
        lhs_12_out_ap_vld,
        lhs_10_out,
        lhs_10_out_ap_vld,
        lhs_8_out,
        lhs_8_out_ap_vld,
        lhs_6_out,
        lhs_6_out_ap_vld,
        lhs_4_out,
        lhs_4_out_ap_vld,
        lhs_2_out,
        lhs_2_out_ap_vld,
        lhs_out,
        lhs_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] buf_V_9_reload;
input  [15:0] buf_V_8_reload;
input  [15:0] buf_V_7_reload;
input  [15:0] buf_V_6_reload;
input  [15:0] buf_V_5_reload;
input  [15:0] buf_V_4_reload;
input  [15:0] buf_V_3_reload;
input  [15:0] buf_V_2_reload;
input  [15:0] buf_V_1_reload;
input  [15:0] buf_V_reload;
output  [5:0] inputs_address0;
output   inputs_ce0;
input  [31:0] inputs_q0;
output  [15:0] lhs_18_out;
output   lhs_18_out_ap_vld;
output  [15:0] lhs_16_out;
output   lhs_16_out_ap_vld;
output  [15:0] lhs_14_out;
output   lhs_14_out_ap_vld;
output  [15:0] lhs_12_out;
output   lhs_12_out_ap_vld;
output  [15:0] lhs_10_out;
output   lhs_10_out_ap_vld;
output  [15:0] lhs_8_out;
output   lhs_8_out_ap_vld;
output  [15:0] lhs_6_out;
output   lhs_6_out_ap_vld;
output  [15:0] lhs_4_out;
output   lhs_4_out_ap_vld;
output  [15:0] lhs_2_out;
output   lhs_2_out_ap_vld;
output  [15:0] lhs_out;
output   lhs_out_ap_vld;

reg ap_idle;
reg inputs_ce0;
reg lhs_18_out_ap_vld;
reg lhs_16_out_ap_vld;
reg lhs_14_out_ap_vld;
reg lhs_12_out_ap_vld;
reg lhs_10_out_ap_vld;
reg lhs_8_out_ap_vld;
reg lhs_6_out_ap_vld;
reg lhs_4_out_ap_vld;
reg lhs_2_out_ap_vld;
reg lhs_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln271_fu_531_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] p_ZL17linear_weight_fix_0_address0;
reg    p_ZL17linear_weight_fix_0_ce0;
wire   [9:0] p_ZL17linear_weight_fix_0_q0;
wire   [5:0] p_ZL17linear_weight_fix_1_address0;
reg    p_ZL17linear_weight_fix_1_ce0;
wire   [9:0] p_ZL17linear_weight_fix_1_q0;
wire   [5:0] p_ZL17linear_weight_fix_2_address0;
reg    p_ZL17linear_weight_fix_2_ce0;
wire   [9:0] p_ZL17linear_weight_fix_2_q0;
wire   [5:0] p_ZL17linear_weight_fix_3_address0;
reg    p_ZL17linear_weight_fix_3_ce0;
wire   [8:0] p_ZL17linear_weight_fix_3_q0;
wire   [5:0] p_ZL17linear_weight_fix_4_address0;
reg    p_ZL17linear_weight_fix_4_ce0;
wire   [9:0] p_ZL17linear_weight_fix_4_q0;
wire   [5:0] p_ZL17linear_weight_fix_5_address0;
reg    p_ZL17linear_weight_fix_5_ce0;
wire   [9:0] p_ZL17linear_weight_fix_5_q0;
wire   [5:0] p_ZL17linear_weight_fix_6_address0;
reg    p_ZL17linear_weight_fix_6_ce0;
wire   [9:0] p_ZL17linear_weight_fix_6_q0;
wire   [5:0] p_ZL17linear_weight_fix_7_address0;
reg    p_ZL17linear_weight_fix_7_ce0;
wire   [9:0] p_ZL17linear_weight_fix_7_q0;
wire   [5:0] p_ZL17linear_weight_fix_8_address0;
reg    p_ZL17linear_weight_fix_8_ce0;
wire   [9:0] p_ZL17linear_weight_fix_8_q0;
wire   [5:0] p_ZL17linear_weight_fix_9_address0;
reg    p_ZL17linear_weight_fix_9_ce0;
wire   [9:0] p_ZL17linear_weight_fix_9_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln271_reg_3782;
reg   [0:0] icmp_ln271_reg_3782_pp0_iter1_reg;
reg   [0:0] icmp_ln271_reg_3782_pp0_iter2_reg;
reg   [0:0] icmp_ln271_reg_3782_pp0_iter3_reg;
reg   [0:0] icmp_ln271_reg_3782_pp0_iter4_reg;
wire   [63:0] zext_ln271_fu_543_p1;
reg   [63:0] zext_ln271_reg_3786;
reg   [0:0] p_Result_s_reg_3805;
reg   [15:0] tmp_in_V_reg_3813;
reg   [0:0] p_Result_65_reg_3818;
reg   [0:0] tmp_66_reg_3824;
wire  signed [25:0] sext_ln1316_1_fu_991_p1;
wire   [23:0] add_ln1393_1_fu_1096_p2;
reg   [23:0] add_ln1393_1_reg_3947;
reg   [0:0] p_Result_67_reg_3952;
reg   [0:0] p_Result_68_reg_3958;
wire   [15:0] p_Val2_65_fu_1145_p2;
reg   [15:0] p_Val2_65_reg_3963;
reg   [0:0] p_Result_69_reg_3968;
wire   [0:0] Range2_all_ones_fu_1169_p2;
reg   [0:0] Range2_all_ones_reg_3974;
wire   [0:0] Range1_all_ones_1_fu_1185_p2;
reg   [0:0] Range1_all_ones_1_reg_3979;
wire   [0:0] Range1_all_zeros_1_fu_1191_p2;
reg   [0:0] Range1_all_zeros_1_reg_3986;
wire   [23:0] add_ln1393_3_fu_1228_p2;
reg   [23:0] add_ln1393_3_reg_3991;
reg   [0:0] p_Result_70_reg_3996;
reg   [0:0] p_Result_71_reg_4002;
wire   [15:0] p_Val2_68_fu_1277_p2;
reg   [15:0] p_Val2_68_reg_4007;
reg   [0:0] p_Result_72_reg_4012;
wire   [0:0] Range2_all_ones_1_fu_1301_p2;
reg   [0:0] Range2_all_ones_1_reg_4018;
wire   [0:0] Range1_all_ones_2_fu_1317_p2;
reg   [0:0] Range1_all_ones_2_reg_4023;
wire   [0:0] Range1_all_zeros_2_fu_1323_p2;
reg   [0:0] Range1_all_zeros_2_reg_4030;
wire   [23:0] add_ln1393_5_fu_1360_p2;
reg   [23:0] add_ln1393_5_reg_4035;
reg   [0:0] p_Result_73_reg_4040;
reg   [0:0] p_Result_74_reg_4046;
wire   [15:0] p_Val2_71_fu_1409_p2;
reg   [15:0] p_Val2_71_reg_4051;
reg   [0:0] p_Result_75_reg_4056;
wire   [0:0] Range2_all_ones_2_fu_1433_p2;
reg   [0:0] Range2_all_ones_2_reg_4062;
wire   [0:0] Range1_all_ones_3_fu_1449_p2;
reg   [0:0] Range1_all_ones_3_reg_4067;
wire   [0:0] Range1_all_zeros_3_fu_1455_p2;
reg   [0:0] Range1_all_zeros_3_reg_4074;
wire   [23:0] add_ln1393_7_fu_1492_p2;
reg   [23:0] add_ln1393_7_reg_4079;
reg   [0:0] p_Result_76_reg_4084;
reg   [0:0] p_Result_77_reg_4090;
wire   [15:0] p_Val2_74_fu_1541_p2;
reg   [15:0] p_Val2_74_reg_4095;
reg   [0:0] p_Result_78_reg_4100;
wire   [0:0] Range2_all_ones_3_fu_1565_p2;
reg   [0:0] Range2_all_ones_3_reg_4106;
wire   [0:0] Range1_all_ones_4_fu_1581_p2;
reg   [0:0] Range1_all_ones_4_reg_4111;
wire   [0:0] Range1_all_zeros_4_fu_1587_p2;
reg   [0:0] Range1_all_zeros_4_reg_4118;
wire   [23:0] add_ln1393_9_fu_1624_p2;
reg   [23:0] add_ln1393_9_reg_4123;
reg   [0:0] p_Result_79_reg_4128;
reg   [0:0] p_Result_80_reg_4134;
wire   [15:0] p_Val2_77_fu_1673_p2;
reg   [15:0] p_Val2_77_reg_4139;
reg   [0:0] p_Result_81_reg_4144;
wire   [0:0] Range2_all_ones_4_fu_1697_p2;
reg   [0:0] Range2_all_ones_4_reg_4150;
wire   [0:0] Range1_all_ones_5_fu_1713_p2;
reg   [0:0] Range1_all_ones_5_reg_4155;
wire   [0:0] Range1_all_zeros_5_fu_1719_p2;
reg   [0:0] Range1_all_zeros_5_reg_4162;
wire   [23:0] add_ln1393_11_fu_1756_p2;
reg   [23:0] add_ln1393_11_reg_4167;
reg   [0:0] p_Result_82_reg_4172;
reg   [0:0] p_Result_83_reg_4178;
wire   [15:0] p_Val2_80_fu_1805_p2;
reg   [15:0] p_Val2_80_reg_4183;
reg   [0:0] p_Result_84_reg_4188;
wire   [0:0] Range2_all_ones_5_fu_1829_p2;
reg   [0:0] Range2_all_ones_5_reg_4194;
wire   [0:0] Range1_all_ones_6_fu_1845_p2;
reg   [0:0] Range1_all_ones_6_reg_4199;
wire   [0:0] Range1_all_zeros_6_fu_1851_p2;
reg   [0:0] Range1_all_zeros_6_reg_4206;
wire   [23:0] add_ln1393_13_fu_1888_p2;
reg   [23:0] add_ln1393_13_reg_4211;
reg   [0:0] p_Result_85_reg_4216;
reg   [0:0] p_Result_86_reg_4222;
wire   [15:0] p_Val2_83_fu_1937_p2;
reg   [15:0] p_Val2_83_reg_4227;
reg   [0:0] p_Result_87_reg_4232;
wire   [0:0] Range2_all_ones_6_fu_1961_p2;
reg   [0:0] Range2_all_ones_6_reg_4238;
wire   [0:0] Range1_all_ones_7_fu_1977_p2;
reg   [0:0] Range1_all_ones_7_reg_4243;
wire   [0:0] Range1_all_zeros_7_fu_1983_p2;
reg   [0:0] Range1_all_zeros_7_reg_4250;
wire   [23:0] add_ln1393_15_fu_2020_p2;
reg   [23:0] add_ln1393_15_reg_4255;
reg   [0:0] p_Result_88_reg_4260;
reg   [0:0] p_Result_89_reg_4266;
wire   [15:0] p_Val2_86_fu_2069_p2;
reg   [15:0] p_Val2_86_reg_4271;
reg   [0:0] p_Result_90_reg_4276;
wire   [0:0] Range2_all_ones_7_fu_2093_p2;
reg   [0:0] Range2_all_ones_7_reg_4282;
wire   [0:0] Range1_all_ones_8_fu_2109_p2;
reg   [0:0] Range1_all_ones_8_reg_4287;
wire   [0:0] Range1_all_zeros_8_fu_2115_p2;
reg   [0:0] Range1_all_zeros_8_reg_4294;
wire   [23:0] add_ln1393_17_fu_2152_p2;
reg   [23:0] add_ln1393_17_reg_4299;
reg   [0:0] p_Result_91_reg_4304;
reg   [0:0] p_Result_92_reg_4310;
wire   [15:0] p_Val2_89_fu_2201_p2;
reg   [15:0] p_Val2_89_reg_4315;
reg   [0:0] p_Result_93_reg_4320;
wire   [0:0] Range2_all_ones_8_fu_2225_p2;
reg   [0:0] Range2_all_ones_8_reg_4326;
wire   [0:0] Range1_all_ones_9_fu_2241_p2;
reg   [0:0] Range1_all_ones_9_reg_4331;
wire   [0:0] Range1_all_zeros_9_fu_2247_p2;
reg   [0:0] Range1_all_zeros_9_reg_4338;
wire   [23:0] add_ln1393_19_fu_2284_p2;
reg   [23:0] add_ln1393_19_reg_4343;
reg   [0:0] p_Result_94_reg_4348;
reg   [0:0] p_Result_95_reg_4354;
wire   [15:0] p_Val2_92_fu_2333_p2;
reg   [15:0] p_Val2_92_reg_4359;
reg   [0:0] p_Result_96_reg_4364;
wire   [0:0] Range2_all_ones_9_fu_2357_p2;
reg   [0:0] Range2_all_ones_9_reg_4370;
wire   [0:0] Range1_all_ones_10_fu_2373_p2;
reg   [0:0] Range1_all_ones_10_reg_4375;
wire   [0:0] Range1_all_zeros_10_fu_2379_p2;
reg   [0:0] Range1_all_zeros_10_reg_4382;
wire    ap_block_pp0_stage0;
reg   [15:0] lhs_fu_156;
wire   [15:0] buf_V_fu_2490_p3;
reg   [15:0] ap_sig_allocacmp_lhs_load_1;
wire    ap_loop_init;
reg   [15:0] lhs_2_fu_160;
wire   [15:0] buf_V_1_fu_2602_p3;
reg   [15:0] ap_sig_allocacmp_lhs_2_load_1;
reg   [15:0] lhs_4_fu_164;
wire   [15:0] buf_V_2_fu_2714_p3;
reg   [15:0] ap_sig_allocacmp_lhs_4_load_1;
reg   [15:0] lhs_6_fu_168;
wire   [15:0] buf_V_3_fu_2826_p3;
reg   [15:0] ap_sig_allocacmp_lhs_6_load_1;
reg   [15:0] lhs_8_fu_172;
wire   [15:0] buf_V_4_fu_2938_p3;
reg   [15:0] ap_sig_allocacmp_lhs_8_load_1;
reg   [15:0] lhs_10_fu_176;
wire   [15:0] buf_V_5_fu_3050_p3;
reg   [15:0] ap_sig_allocacmp_lhs_10_load_1;
reg   [15:0] lhs_12_fu_180;
wire   [15:0] buf_V_6_fu_3162_p3;
reg   [15:0] ap_sig_allocacmp_lhs_12_load_1;
reg   [15:0] lhs_14_fu_184;
wire   [15:0] buf_V_7_fu_3274_p3;
reg   [15:0] ap_sig_allocacmp_lhs_14_load_1;
reg   [15:0] lhs_16_fu_188;
wire   [15:0] buf_V_8_fu_3386_p3;
reg   [15:0] ap_sig_allocacmp_lhs_16_load_1;
reg   [15:0] lhs_18_fu_192;
wire   [15:0] buf_V_9_fu_3498_p3;
reg   [15:0] ap_sig_allocacmp_lhs_18_load_1;
reg   [6:0] cii_fu_196;
wire   [6:0] add_ln271_fu_537_p2;
reg   [6:0] ap_sig_allocacmp_cii_1;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] zext_ln423_fu_587_p1;
wire   [15:0] tmp_in_V_1_fu_590_p2;
wire   [0:0] p_Result_66_fu_595_p3;
wire   [0:0] xor_ln942_fu_603_p2;
wire   [0:0] carry_1_fu_609_p2;
wire   [0:0] Range1_all_zeros_fu_614_p2;
wire   [0:0] xor_ln937_fu_633_p2;
wire   [0:0] deleted_zeros_fu_619_p3;
wire   [0:0] xor_ln941_fu_644_p2;
wire   [0:0] or_ln941_fu_650_p2;
wire   [0:0] deleted_ones_fu_626_p3;
wire   [0:0] xor_ln942_1_fu_662_p2;
wire   [0:0] or_ln937_fu_638_p2;
wire   [0:0] and_ln942_fu_674_p2;
wire   [0:0] or_ln942_fu_668_p2;
wire   [0:0] overflow_fu_656_p2;
wire   [0:0] underflow_fu_679_p2;
wire   [0:0] or_ln392_fu_693_p2;
wire   [15:0] select_ln392_1_fu_685_p3;
wire   [8:0] trunc_ln864_2_fu_711_p4;
wire   [0:0] trunc_ln864_fu_707_p1;
wire   [9:0] zext_ln423_1_fu_725_p1;
wire  signed [9:0] sext_ln869_fu_721_p1;
wire   [8:0] trunc_ln864_4_fu_739_p4;
wire   [0:0] trunc_ln864_1_fu_735_p1;
wire   [9:0] zext_ln423_2_fu_753_p1;
wire  signed [9:0] sext_ln869_1_fu_749_p1;
wire   [8:0] trunc_ln864_6_fu_767_p4;
wire   [0:0] trunc_ln864_3_fu_763_p1;
wire   [9:0] zext_ln423_3_fu_781_p1;
wire  signed [9:0] sext_ln869_2_fu_777_p1;
wire   [7:0] trunc_ln864_8_fu_795_p4;
wire   [0:0] trunc_ln864_5_fu_791_p1;
wire   [8:0] zext_ln423_4_fu_809_p1;
wire  signed [8:0] sext_ln869_3_fu_805_p1;
wire   [8:0] trunc_ln864_s_fu_823_p4;
wire   [0:0] trunc_ln864_7_fu_819_p1;
wire   [9:0] zext_ln423_5_fu_837_p1;
wire  signed [9:0] sext_ln869_4_fu_833_p1;
wire   [8:0] trunc_ln864_10_fu_851_p4;
wire   [0:0] trunc_ln864_9_fu_847_p1;
wire   [9:0] zext_ln423_6_fu_865_p1;
wire  signed [9:0] sext_ln869_5_fu_861_p1;
wire   [8:0] trunc_ln864_12_fu_879_p4;
wire   [0:0] trunc_ln864_11_fu_875_p1;
wire   [9:0] zext_ln423_7_fu_893_p1;
wire  signed [9:0] sext_ln869_6_fu_889_p1;
wire   [8:0] trunc_ln864_14_fu_907_p4;
wire   [0:0] trunc_ln864_13_fu_903_p1;
wire   [9:0] zext_ln423_8_fu_921_p1;
wire  signed [9:0] sext_ln869_7_fu_917_p1;
wire   [8:0] trunc_ln864_16_fu_935_p4;
wire   [0:0] trunc_ln864_15_fu_931_p1;
wire   [9:0] zext_ln423_9_fu_949_p1;
wire  signed [9:0] sext_ln869_8_fu_945_p1;
wire   [8:0] trunc_ln864_18_fu_963_p4;
wire   [0:0] trunc_ln864_17_fu_959_p1;
wire   [9:0] zext_ln423_10_fu_977_p1;
wire  signed [9:0] sext_ln869_9_fu_973_p1;
wire  signed [15:0] tmp_in_V_2_fu_699_p3;
wire  signed [9:0] tmp_wt_V_fu_729_p2;
wire  signed [9:0] tmp_wt_V_1_fu_757_p2;
wire  signed [9:0] tmp_wt_V_2_fu_785_p2;
wire  signed [8:0] tmp_wt_V_3_fu_813_p2;
wire  signed [9:0] tmp_wt_V_4_fu_841_p2;
wire  signed [9:0] tmp_wt_V_5_fu_869_p2;
wire  signed [9:0] tmp_wt_V_6_fu_897_p2;
wire  signed [9:0] tmp_wt_V_7_fu_925_p2;
wire  signed [9:0] tmp_wt_V_8_fu_953_p2;
wire  signed [9:0] tmp_wt_V_9_fu_981_p2;
wire  signed [22:0] lhs_1_fu_1065_p3;
wire  signed [25:0] grp_fu_3595_p2;
wire  signed [26:0] sext_ln1393_fu_1073_p1;
wire  signed [26:0] sext_ln1393_20_fu_1077_p1;
wire  signed [23:0] sext_ln1393_1_fu_1086_p1;
wire   [23:0] trunc_ln1393_1_fu_1083_p1;
wire   [22:0] trunc_ln1393_fu_1080_p1;
wire   [26:0] ret_V_fu_1090_p2;
wire   [22:0] add_ln1393_2_fu_1102_p2;
wire   [0:0] tmp_70_fu_1134_p3;
wire   [15:0] zext_ln423_11_fu_1141_p1;
wire   [15:0] p_Val2_64_fu_1116_p4;
wire   [2:0] tmp_fu_1159_p4;
wire   [3:0] tmp_1_fu_1175_p4;
wire  signed [22:0] lhs_3_fu_1197_p3;
wire  signed [25:0] grp_fu_3605_p2;
wire  signed [26:0] sext_ln1393_2_fu_1205_p1;
wire  signed [26:0] sext_ln1393_21_fu_1209_p1;
wire  signed [23:0] sext_ln1393_3_fu_1218_p1;
wire   [23:0] trunc_ln1393_3_fu_1215_p1;
wire   [22:0] trunc_ln1393_2_fu_1212_p1;
wire   [26:0] ret_V_1_fu_1222_p2;
wire   [22:0] add_ln1393_4_fu_1234_p2;
wire   [0:0] tmp_75_fu_1266_p3;
wire   [15:0] zext_ln423_12_fu_1273_p1;
wire   [15:0] p_Val2_67_fu_1248_p4;
wire   [2:0] tmp_2_fu_1291_p4;
wire   [3:0] tmp_3_fu_1307_p4;
wire  signed [22:0] lhs_5_fu_1329_p3;
wire  signed [25:0] grp_fu_3615_p2;
wire  signed [26:0] sext_ln1393_4_fu_1337_p1;
wire  signed [26:0] sext_ln1393_22_fu_1341_p1;
wire  signed [23:0] sext_ln1393_5_fu_1350_p1;
wire   [23:0] trunc_ln1393_5_fu_1347_p1;
wire   [22:0] trunc_ln1393_4_fu_1344_p1;
wire   [26:0] ret_V_2_fu_1354_p2;
wire   [22:0] add_ln1393_6_fu_1366_p2;
wire   [0:0] tmp_80_fu_1398_p3;
wire   [15:0] zext_ln423_13_fu_1405_p1;
wire   [15:0] p_Val2_70_fu_1380_p4;
wire   [2:0] tmp_4_fu_1423_p4;
wire   [3:0] tmp_5_fu_1439_p4;
wire  signed [22:0] lhs_7_fu_1461_p3;
wire  signed [24:0] grp_fu_3625_p2;
wire  signed [26:0] sext_ln1393_6_fu_1469_p1;
wire  signed [26:0] sext_ln1393_23_fu_1473_p1;
wire  signed [23:0] sext_ln1393_7_fu_1482_p1;
wire   [23:0] trunc_ln1393_7_fu_1479_p1;
wire   [22:0] trunc_ln1393_6_fu_1476_p1;
wire   [26:0] ret_V_3_fu_1486_p2;
wire   [22:0] add_ln1393_8_fu_1498_p2;
wire   [0:0] tmp_85_fu_1530_p3;
wire   [15:0] zext_ln423_14_fu_1537_p1;
wire   [15:0] p_Val2_73_fu_1512_p4;
wire   [2:0] tmp_6_fu_1555_p4;
wire   [3:0] tmp_7_fu_1571_p4;
wire  signed [22:0] lhs_9_fu_1593_p3;
wire  signed [25:0] grp_fu_3635_p2;
wire  signed [26:0] sext_ln1393_8_fu_1601_p1;
wire  signed [26:0] sext_ln1393_24_fu_1605_p1;
wire  signed [23:0] sext_ln1393_9_fu_1614_p1;
wire   [23:0] trunc_ln1393_9_fu_1611_p1;
wire   [22:0] trunc_ln1393_8_fu_1608_p1;
wire   [26:0] ret_V_4_fu_1618_p2;
wire   [22:0] add_ln1393_10_fu_1630_p2;
wire   [0:0] tmp_90_fu_1662_p3;
wire   [15:0] zext_ln423_15_fu_1669_p1;
wire   [15:0] p_Val2_76_fu_1644_p4;
wire   [2:0] tmp_8_fu_1687_p4;
wire   [3:0] tmp_9_fu_1703_p4;
wire  signed [22:0] lhs_20_fu_1725_p3;
wire  signed [25:0] grp_fu_3645_p2;
wire  signed [26:0] sext_ln1393_10_fu_1733_p1;
wire  signed [26:0] sext_ln1393_25_fu_1737_p1;
wire  signed [23:0] sext_ln1393_11_fu_1746_p1;
wire   [23:0] trunc_ln1393_11_fu_1743_p1;
wire   [22:0] trunc_ln1393_10_fu_1740_p1;
wire   [26:0] ret_V_5_fu_1750_p2;
wire   [22:0] add_ln1393_12_fu_1762_p2;
wire   [0:0] tmp_95_fu_1794_p3;
wire   [15:0] zext_ln423_16_fu_1801_p1;
wire   [15:0] p_Val2_79_fu_1776_p4;
wire   [2:0] tmp_10_fu_1819_p4;
wire   [3:0] tmp_11_fu_1835_p4;
wire  signed [22:0] lhs_21_fu_1857_p3;
wire  signed [25:0] grp_fu_3655_p2;
wire  signed [26:0] sext_ln1393_12_fu_1865_p1;
wire  signed [26:0] sext_ln1393_26_fu_1869_p1;
wire  signed [23:0] sext_ln1393_13_fu_1878_p1;
wire   [23:0] trunc_ln1393_13_fu_1875_p1;
wire   [22:0] trunc_ln1393_12_fu_1872_p1;
wire   [26:0] ret_V_6_fu_1882_p2;
wire   [22:0] add_ln1393_14_fu_1894_p2;
wire   [0:0] tmp_100_fu_1926_p3;
wire   [15:0] zext_ln423_17_fu_1933_p1;
wire   [15:0] p_Val2_82_fu_1908_p4;
wire   [2:0] tmp_12_fu_1951_p4;
wire   [3:0] tmp_13_fu_1967_p4;
wire  signed [22:0] lhs_22_fu_1989_p3;
wire  signed [25:0] grp_fu_3665_p2;
wire  signed [26:0] sext_ln1393_14_fu_1997_p1;
wire  signed [26:0] sext_ln1393_27_fu_2001_p1;
wire  signed [23:0] sext_ln1393_15_fu_2010_p1;
wire   [23:0] trunc_ln1393_15_fu_2007_p1;
wire   [22:0] trunc_ln1393_14_fu_2004_p1;
wire   [26:0] ret_V_7_fu_2014_p2;
wire   [22:0] add_ln1393_16_fu_2026_p2;
wire   [0:0] tmp_105_fu_2058_p3;
wire   [15:0] zext_ln423_18_fu_2065_p1;
wire   [15:0] p_Val2_85_fu_2040_p4;
wire   [2:0] tmp_14_fu_2083_p4;
wire   [3:0] tmp_15_fu_2099_p4;
wire  signed [22:0] lhs_23_fu_2121_p3;
wire  signed [25:0] grp_fu_3675_p2;
wire  signed [26:0] sext_ln1393_16_fu_2129_p1;
wire  signed [26:0] sext_ln1393_28_fu_2133_p1;
wire  signed [23:0] sext_ln1393_17_fu_2142_p1;
wire   [23:0] trunc_ln1393_17_fu_2139_p1;
wire   [22:0] trunc_ln1393_16_fu_2136_p1;
wire   [26:0] ret_V_8_fu_2146_p2;
wire   [22:0] add_ln1393_18_fu_2158_p2;
wire   [0:0] tmp_110_fu_2190_p3;
wire   [15:0] zext_ln423_19_fu_2197_p1;
wire   [15:0] p_Val2_88_fu_2172_p4;
wire   [2:0] tmp_s_fu_2215_p4;
wire   [3:0] tmp_16_fu_2231_p4;
wire  signed [22:0] lhs_24_fu_2253_p3;
wire  signed [25:0] grp_fu_3685_p2;
wire  signed [26:0] sext_ln1393_18_fu_2261_p1;
wire  signed [26:0] sext_ln1393_29_fu_2265_p1;
wire  signed [23:0] sext_ln1393_19_fu_2274_p1;
wire   [23:0] trunc_ln1393_19_fu_2271_p1;
wire   [22:0] trunc_ln1393_18_fu_2268_p1;
wire   [26:0] ret_V_9_fu_2278_p2;
wire   [22:0] add_ln1393_20_fu_2290_p2;
wire   [0:0] tmp_115_fu_2322_p3;
wire   [15:0] zext_ln423_20_fu_2329_p1;
wire   [15:0] p_Val2_91_fu_2304_p4;
wire   [2:0] tmp_17_fu_2347_p4;
wire   [3:0] tmp_18_fu_2363_p4;
wire   [0:0] xor_ln942_2_fu_2385_p2;
wire   [0:0] carry_3_fu_2390_p2;
wire   [0:0] tmp_72_fu_2401_p3;
wire   [0:0] xor_ln936_fu_2408_p2;
wire   [0:0] and_ln936_fu_2414_p2;
wire   [0:0] deleted_zeros_1_fu_2395_p3;
wire   [0:0] xor_ln941_1_fu_2431_p2;
wire   [0:0] or_ln941_1_fu_2437_p2;
wire   [0:0] xor_ln941_2_fu_2442_p2;
wire   [0:0] deleted_ones_1_fu_2419_p3;
wire   [0:0] xor_ln942_3_fu_2453_p2;
wire   [0:0] and_ln937_fu_2426_p2;
wire   [0:0] or_ln942_1_fu_2459_p2;
wire   [0:0] xor_ln942_22_fu_2465_p2;
wire   [0:0] overflow_1_fu_2447_p2;
wire   [0:0] underflow_1_fu_2471_p2;
wire   [0:0] or_ln392_1_fu_2484_p2;
wire   [15:0] select_ln392_fu_2476_p3;
wire   [0:0] xor_ln942_4_fu_2497_p2;
wire   [0:0] carry_5_fu_2502_p2;
wire   [0:0] tmp_77_fu_2513_p3;
wire   [0:0] xor_ln936_1_fu_2520_p2;
wire   [0:0] and_ln936_1_fu_2526_p2;
wire   [0:0] deleted_zeros_2_fu_2507_p3;
wire   [0:0] xor_ln941_3_fu_2543_p2;
wire   [0:0] or_ln941_2_fu_2549_p2;
wire   [0:0] xor_ln941_4_fu_2554_p2;
wire   [0:0] deleted_ones_2_fu_2531_p3;
wire   [0:0] xor_ln942_5_fu_2565_p2;
wire   [0:0] and_ln937_1_fu_2538_p2;
wire   [0:0] or_ln942_2_fu_2571_p2;
wire   [0:0] xor_ln942_23_fu_2577_p2;
wire   [0:0] overflow_2_fu_2559_p2;
wire   [0:0] underflow_2_fu_2583_p2;
wire   [0:0] or_ln392_2_fu_2596_p2;
wire   [15:0] select_ln392_4_fu_2588_p3;
wire   [0:0] xor_ln942_6_fu_2609_p2;
wire   [0:0] carry_7_fu_2614_p2;
wire   [0:0] tmp_82_fu_2625_p3;
wire   [0:0] xor_ln936_2_fu_2632_p2;
wire   [0:0] and_ln936_2_fu_2638_p2;
wire   [0:0] deleted_zeros_3_fu_2619_p3;
wire   [0:0] xor_ln941_5_fu_2655_p2;
wire   [0:0] or_ln941_3_fu_2661_p2;
wire   [0:0] xor_ln941_6_fu_2666_p2;
wire   [0:0] deleted_ones_3_fu_2643_p3;
wire   [0:0] xor_ln942_7_fu_2677_p2;
wire   [0:0] and_ln937_2_fu_2650_p2;
wire   [0:0] or_ln942_3_fu_2683_p2;
wire   [0:0] xor_ln942_24_fu_2689_p2;
wire   [0:0] overflow_3_fu_2671_p2;
wire   [0:0] underflow_3_fu_2695_p2;
wire   [0:0] or_ln392_3_fu_2708_p2;
wire   [15:0] select_ln392_6_fu_2700_p3;
wire   [0:0] xor_ln942_8_fu_2721_p2;
wire   [0:0] carry_9_fu_2726_p2;
wire   [0:0] tmp_87_fu_2737_p3;
wire   [0:0] xor_ln936_3_fu_2744_p2;
wire   [0:0] and_ln936_3_fu_2750_p2;
wire   [0:0] deleted_zeros_4_fu_2731_p3;
wire   [0:0] xor_ln941_7_fu_2767_p2;
wire   [0:0] or_ln941_4_fu_2773_p2;
wire   [0:0] xor_ln941_8_fu_2778_p2;
wire   [0:0] deleted_ones_4_fu_2755_p3;
wire   [0:0] xor_ln942_9_fu_2789_p2;
wire   [0:0] and_ln937_3_fu_2762_p2;
wire   [0:0] or_ln942_4_fu_2795_p2;
wire   [0:0] xor_ln942_25_fu_2801_p2;
wire   [0:0] overflow_4_fu_2783_p2;
wire   [0:0] underflow_4_fu_2807_p2;
wire   [0:0] or_ln392_4_fu_2820_p2;
wire   [15:0] select_ln392_8_fu_2812_p3;
wire   [0:0] xor_ln942_10_fu_2833_p2;
wire   [0:0] carry_11_fu_2838_p2;
wire   [0:0] tmp_92_fu_2849_p3;
wire   [0:0] xor_ln936_4_fu_2856_p2;
wire   [0:0] and_ln936_4_fu_2862_p2;
wire   [0:0] deleted_zeros_5_fu_2843_p3;
wire   [0:0] xor_ln941_9_fu_2879_p2;
wire   [0:0] or_ln941_5_fu_2885_p2;
wire   [0:0] xor_ln941_10_fu_2890_p2;
wire   [0:0] deleted_ones_5_fu_2867_p3;
wire   [0:0] xor_ln942_11_fu_2901_p2;
wire   [0:0] and_ln937_4_fu_2874_p2;
wire   [0:0] or_ln942_5_fu_2907_p2;
wire   [0:0] xor_ln942_26_fu_2913_p2;
wire   [0:0] overflow_5_fu_2895_p2;
wire   [0:0] underflow_5_fu_2919_p2;
wire   [0:0] or_ln392_5_fu_2932_p2;
wire   [15:0] select_ln392_10_fu_2924_p3;
wire   [0:0] xor_ln942_12_fu_2945_p2;
wire   [0:0] carry_13_fu_2950_p2;
wire   [0:0] tmp_97_fu_2961_p3;
wire   [0:0] xor_ln936_5_fu_2968_p2;
wire   [0:0] and_ln936_5_fu_2974_p2;
wire   [0:0] deleted_zeros_6_fu_2955_p3;
wire   [0:0] xor_ln941_11_fu_2991_p2;
wire   [0:0] or_ln941_6_fu_2997_p2;
wire   [0:0] xor_ln941_12_fu_3002_p2;
wire   [0:0] deleted_ones_6_fu_2979_p3;
wire   [0:0] xor_ln942_13_fu_3013_p2;
wire   [0:0] and_ln937_5_fu_2986_p2;
wire   [0:0] or_ln942_6_fu_3019_p2;
wire   [0:0] xor_ln942_27_fu_3025_p2;
wire   [0:0] overflow_6_fu_3007_p2;
wire   [0:0] underflow_6_fu_3031_p2;
wire   [0:0] or_ln392_6_fu_3044_p2;
wire   [15:0] select_ln392_12_fu_3036_p3;
wire   [0:0] xor_ln942_14_fu_3057_p2;
wire   [0:0] carry_15_fu_3062_p2;
wire   [0:0] tmp_102_fu_3073_p3;
wire   [0:0] xor_ln936_6_fu_3080_p2;
wire   [0:0] and_ln936_6_fu_3086_p2;
wire   [0:0] deleted_zeros_7_fu_3067_p3;
wire   [0:0] xor_ln941_13_fu_3103_p2;
wire   [0:0] or_ln941_7_fu_3109_p2;
wire   [0:0] xor_ln941_14_fu_3114_p2;
wire   [0:0] deleted_ones_7_fu_3091_p3;
wire   [0:0] xor_ln942_15_fu_3125_p2;
wire   [0:0] and_ln937_6_fu_3098_p2;
wire   [0:0] or_ln942_7_fu_3131_p2;
wire   [0:0] xor_ln942_28_fu_3137_p2;
wire   [0:0] overflow_7_fu_3119_p2;
wire   [0:0] underflow_7_fu_3143_p2;
wire   [0:0] or_ln392_7_fu_3156_p2;
wire   [15:0] select_ln392_14_fu_3148_p3;
wire   [0:0] xor_ln942_16_fu_3169_p2;
wire   [0:0] carry_17_fu_3174_p2;
wire   [0:0] tmp_107_fu_3185_p3;
wire   [0:0] xor_ln936_7_fu_3192_p2;
wire   [0:0] and_ln936_7_fu_3198_p2;
wire   [0:0] deleted_zeros_8_fu_3179_p3;
wire   [0:0] xor_ln941_15_fu_3215_p2;
wire   [0:0] or_ln941_8_fu_3221_p2;
wire   [0:0] xor_ln941_16_fu_3226_p2;
wire   [0:0] deleted_ones_8_fu_3203_p3;
wire   [0:0] xor_ln942_17_fu_3237_p2;
wire   [0:0] and_ln937_7_fu_3210_p2;
wire   [0:0] or_ln942_8_fu_3243_p2;
wire   [0:0] xor_ln942_29_fu_3249_p2;
wire   [0:0] overflow_8_fu_3231_p2;
wire   [0:0] underflow_8_fu_3255_p2;
wire   [0:0] or_ln392_8_fu_3268_p2;
wire   [15:0] select_ln392_16_fu_3260_p3;
wire   [0:0] xor_ln942_18_fu_3281_p2;
wire   [0:0] carry_19_fu_3286_p2;
wire   [0:0] tmp_112_fu_3297_p3;
wire   [0:0] xor_ln936_8_fu_3304_p2;
wire   [0:0] and_ln936_8_fu_3310_p2;
wire   [0:0] deleted_zeros_9_fu_3291_p3;
wire   [0:0] xor_ln941_17_fu_3327_p2;
wire   [0:0] or_ln941_9_fu_3333_p2;
wire   [0:0] xor_ln941_18_fu_3338_p2;
wire   [0:0] deleted_ones_9_fu_3315_p3;
wire   [0:0] xor_ln942_19_fu_3349_p2;
wire   [0:0] and_ln937_8_fu_3322_p2;
wire   [0:0] or_ln942_9_fu_3355_p2;
wire   [0:0] xor_ln942_30_fu_3361_p2;
wire   [0:0] overflow_9_fu_3343_p2;
wire   [0:0] underflow_9_fu_3367_p2;
wire   [0:0] or_ln392_9_fu_3380_p2;
wire   [15:0] select_ln392_18_fu_3372_p3;
wire   [0:0] xor_ln942_20_fu_3393_p2;
wire   [0:0] carry_21_fu_3398_p2;
wire   [0:0] tmp_117_fu_3409_p3;
wire   [0:0] xor_ln936_9_fu_3416_p2;
wire   [0:0] and_ln936_9_fu_3422_p2;
wire   [0:0] deleted_zeros_10_fu_3403_p3;
wire   [0:0] xor_ln941_19_fu_3439_p2;
wire   [0:0] or_ln941_10_fu_3445_p2;
wire   [0:0] xor_ln941_20_fu_3450_p2;
wire   [0:0] deleted_ones_10_fu_3427_p3;
wire   [0:0] xor_ln942_21_fu_3461_p2;
wire   [0:0] and_ln937_9_fu_3434_p2;
wire   [0:0] or_ln942_10_fu_3467_p2;
wire   [0:0] xor_ln942_31_fu_3473_p2;
wire   [0:0] overflow_10_fu_3455_p2;
wire   [0:0] underflow_10_fu_3479_p2;
wire   [0:0] or_ln392_10_fu_3492_p2;
wire   [15:0] select_ln392_20_fu_3484_p3;
wire  signed [15:0] grp_fu_3595_p1;
wire  signed [15:0] grp_fu_3605_p1;
wire  signed [15:0] grp_fu_3615_p1;
wire  signed [15:0] grp_fu_3635_p1;
wire  signed [15:0] grp_fu_3645_p1;
wire  signed [15:0] grp_fu_3655_p1;
wire  signed [15:0] grp_fu_3665_p1;
wire  signed [15:0] grp_fu_3675_p1;
wire  signed [15:0] grp_fu_3685_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_0_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_0_address0),
    .ce0(p_ZL17linear_weight_fix_0_ce0),
    .q0(p_ZL17linear_weight_fix_0_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_1_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_1_address0),
    .ce0(p_ZL17linear_weight_fix_1_ce0),
    .q0(p_ZL17linear_weight_fix_1_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_2_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_2_address0),
    .ce0(p_ZL17linear_weight_fix_2_ce0),
    .q0(p_ZL17linear_weight_fix_2_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_3_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_3_address0),
    .ce0(p_ZL17linear_weight_fix_3_ce0),
    .q0(p_ZL17linear_weight_fix_3_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_4_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_4_address0),
    .ce0(p_ZL17linear_weight_fix_4_ce0),
    .q0(p_ZL17linear_weight_fix_4_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_5_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_5_address0),
    .ce0(p_ZL17linear_weight_fix_5_ce0),
    .q0(p_ZL17linear_weight_fix_5_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_6_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_6_address0),
    .ce0(p_ZL17linear_weight_fix_6_ce0),
    .q0(p_ZL17linear_weight_fix_6_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_7_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_7_address0),
    .ce0(p_ZL17linear_weight_fix_7_ce0),
    .q0(p_ZL17linear_weight_fix_7_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_8_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_8_address0),
    .ce0(p_ZL17linear_weight_fix_8_ce0),
    .q0(p_ZL17linear_weight_fix_8_q0)
);

FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2_p_ZL17linear_weight_fix_9_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL17linear_weight_fix_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL17linear_weight_fix_9_address0),
    .ce0(p_ZL17linear_weight_fix_9_ce0),
    .q0(p_ZL17linear_weight_fix_9_q0)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2683(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_fu_729_p2),
    .din1(grp_fu_3595_p1),
    .ce(1'b1),
    .dout(grp_fu_3595_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2684(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_1_fu_757_p2),
    .din1(grp_fu_3605_p1),
    .ce(1'b1),
    .dout(grp_fu_3605_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2685(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_2_fu_785_p2),
    .din1(grp_fu_3615_p1),
    .ce(1'b1),
    .dout(grp_fu_3615_p2)
);

FracNet_T_mul_mul_9s_16s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 25 ))
mul_mul_9s_16s_25_4_1_U2686(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_3_fu_813_p2),
    .din1(tmp_in_V_2_fu_699_p3),
    .ce(1'b1),
    .dout(grp_fu_3625_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2687(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_4_fu_841_p2),
    .din1(grp_fu_3635_p1),
    .ce(1'b1),
    .dout(grp_fu_3635_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2688(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_5_fu_869_p2),
    .din1(grp_fu_3645_p1),
    .ce(1'b1),
    .dout(grp_fu_3645_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2689(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_6_fu_897_p2),
    .din1(grp_fu_3655_p1),
    .ce(1'b1),
    .dout(grp_fu_3655_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2690(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_7_fu_925_p2),
    .din1(grp_fu_3665_p1),
    .ce(1'b1),
    .dout(grp_fu_3665_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2691(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_8_fu_953_p2),
    .din1(grp_fu_3675_p1),
    .ce(1'b1),
    .dout(grp_fu_3675_p2)
);

FracNet_T_mul_mul_10s_16s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_mul_10s_16s_26_4_1_U2692(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_wt_V_9_fu_981_p2),
    .din1(grp_fu_3685_p1),
    .ce(1'b1),
    .dout(grp_fu_3685_p2)
);

FracNet_T_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln271_fu_531_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            cii_fu_196 <= add_ln271_fu_537_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            cii_fu_196 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_10_fu_176 <= buf_V_5_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_10_fu_176 <= buf_V_5_fu_3050_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_12_fu_180 <= buf_V_6_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_12_fu_180 <= buf_V_6_fu_3162_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_14_fu_184 <= buf_V_7_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_14_fu_184 <= buf_V_7_fu_3274_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_16_fu_188 <= buf_V_8_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_16_fu_188 <= buf_V_8_fu_3386_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_18_fu_192 <= buf_V_9_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_18_fu_192 <= buf_V_9_fu_3498_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_2_fu_160 <= buf_V_1_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_2_fu_160 <= buf_V_1_fu_2602_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_4_fu_164 <= buf_V_2_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_4_fu_164 <= buf_V_2_fu_2714_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_6_fu_168 <= buf_V_3_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_6_fu_168 <= buf_V_3_fu_2826_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_8_fu_172 <= buf_V_4_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_8_fu_172 <= buf_V_4_fu_2938_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_fu_156 <= buf_V_reload;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            lhs_fu_156 <= buf_V_fu_2490_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Range1_all_ones_10_reg_4375 <= Range1_all_ones_10_fu_2373_p2;
        Range1_all_ones_1_reg_3979 <= Range1_all_ones_1_fu_1185_p2;
        Range1_all_ones_2_reg_4023 <= Range1_all_ones_2_fu_1317_p2;
        Range1_all_ones_3_reg_4067 <= Range1_all_ones_3_fu_1449_p2;
        Range1_all_ones_4_reg_4111 <= Range1_all_ones_4_fu_1581_p2;
        Range1_all_ones_5_reg_4155 <= Range1_all_ones_5_fu_1713_p2;
        Range1_all_ones_6_reg_4199 <= Range1_all_ones_6_fu_1845_p2;
        Range1_all_ones_7_reg_4243 <= Range1_all_ones_7_fu_1977_p2;
        Range1_all_ones_8_reg_4287 <= Range1_all_ones_8_fu_2109_p2;
        Range1_all_ones_9_reg_4331 <= Range1_all_ones_9_fu_2241_p2;
        Range1_all_zeros_10_reg_4382 <= Range1_all_zeros_10_fu_2379_p2;
        Range1_all_zeros_1_reg_3986 <= Range1_all_zeros_1_fu_1191_p2;
        Range1_all_zeros_2_reg_4030 <= Range1_all_zeros_2_fu_1323_p2;
        Range1_all_zeros_3_reg_4074 <= Range1_all_zeros_3_fu_1455_p2;
        Range1_all_zeros_4_reg_4118 <= Range1_all_zeros_4_fu_1587_p2;
        Range1_all_zeros_5_reg_4162 <= Range1_all_zeros_5_fu_1719_p2;
        Range1_all_zeros_6_reg_4206 <= Range1_all_zeros_6_fu_1851_p2;
        Range1_all_zeros_7_reg_4250 <= Range1_all_zeros_7_fu_1983_p2;
        Range1_all_zeros_8_reg_4294 <= Range1_all_zeros_8_fu_2115_p2;
        Range1_all_zeros_9_reg_4338 <= Range1_all_zeros_9_fu_2247_p2;
        Range2_all_ones_1_reg_4018 <= Range2_all_ones_1_fu_1301_p2;
        Range2_all_ones_2_reg_4062 <= Range2_all_ones_2_fu_1433_p2;
        Range2_all_ones_3_reg_4106 <= Range2_all_ones_3_fu_1565_p2;
        Range2_all_ones_4_reg_4150 <= Range2_all_ones_4_fu_1697_p2;
        Range2_all_ones_5_reg_4194 <= Range2_all_ones_5_fu_1829_p2;
        Range2_all_ones_6_reg_4238 <= Range2_all_ones_6_fu_1961_p2;
        Range2_all_ones_7_reg_4282 <= Range2_all_ones_7_fu_2093_p2;
        Range2_all_ones_8_reg_4326 <= Range2_all_ones_8_fu_2225_p2;
        Range2_all_ones_9_reg_4370 <= Range2_all_ones_9_fu_2357_p2;
        Range2_all_ones_reg_3974 <= Range2_all_ones_fu_1169_p2;
        add_ln1393_11_reg_4167 <= add_ln1393_11_fu_1756_p2;
        add_ln1393_13_reg_4211 <= add_ln1393_13_fu_1888_p2;
        add_ln1393_15_reg_4255 <= add_ln1393_15_fu_2020_p2;
        add_ln1393_17_reg_4299 <= add_ln1393_17_fu_2152_p2;
        add_ln1393_19_reg_4343 <= add_ln1393_19_fu_2284_p2;
        add_ln1393_1_reg_3947 <= add_ln1393_1_fu_1096_p2;
        add_ln1393_3_reg_3991 <= add_ln1393_3_fu_1228_p2;
        add_ln1393_5_reg_4035 <= add_ln1393_5_fu_1360_p2;
        add_ln1393_7_reg_4079 <= add_ln1393_7_fu_1492_p2;
        add_ln1393_9_reg_4123 <= add_ln1393_9_fu_1624_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln271_reg_3782_pp0_iter2_reg <= icmp_ln271_reg_3782_pp0_iter1_reg;
        icmp_ln271_reg_3782_pp0_iter3_reg <= icmp_ln271_reg_3782_pp0_iter2_reg;
        icmp_ln271_reg_3782_pp0_iter4_reg <= icmp_ln271_reg_3782_pp0_iter3_reg;
        p_Result_67_reg_3952 <= ret_V_fu_1090_p2[32'd26];
        p_Result_68_reg_3958 <= add_ln1393_2_fu_1102_p2[32'd22];
        p_Result_69_reg_3968 <= p_Val2_65_fu_1145_p2[32'd15];
        p_Result_70_reg_3996 <= ret_V_1_fu_1222_p2[32'd26];
        p_Result_71_reg_4002 <= add_ln1393_4_fu_1234_p2[32'd22];
        p_Result_72_reg_4012 <= p_Val2_68_fu_1277_p2[32'd15];
        p_Result_73_reg_4040 <= ret_V_2_fu_1354_p2[32'd26];
        p_Result_74_reg_4046 <= add_ln1393_6_fu_1366_p2[32'd22];
        p_Result_75_reg_4056 <= p_Val2_71_fu_1409_p2[32'd15];
        p_Result_76_reg_4084 <= ret_V_3_fu_1486_p2[32'd26];
        p_Result_77_reg_4090 <= add_ln1393_8_fu_1498_p2[32'd22];
        p_Result_78_reg_4100 <= p_Val2_74_fu_1541_p2[32'd15];
        p_Result_79_reg_4128 <= ret_V_4_fu_1618_p2[32'd26];
        p_Result_80_reg_4134 <= add_ln1393_10_fu_1630_p2[32'd22];
        p_Result_81_reg_4144 <= p_Val2_77_fu_1673_p2[32'd15];
        p_Result_82_reg_4172 <= ret_V_5_fu_1750_p2[32'd26];
        p_Result_83_reg_4178 <= add_ln1393_12_fu_1762_p2[32'd22];
        p_Result_84_reg_4188 <= p_Val2_80_fu_1805_p2[32'd15];
        p_Result_85_reg_4216 <= ret_V_6_fu_1882_p2[32'd26];
        p_Result_86_reg_4222 <= add_ln1393_14_fu_1894_p2[32'd22];
        p_Result_87_reg_4232 <= p_Val2_83_fu_1937_p2[32'd15];
        p_Result_88_reg_4260 <= ret_V_7_fu_2014_p2[32'd26];
        p_Result_89_reg_4266 <= add_ln1393_16_fu_2026_p2[32'd22];
        p_Result_90_reg_4276 <= p_Val2_86_fu_2069_p2[32'd15];
        p_Result_91_reg_4304 <= ret_V_8_fu_2146_p2[32'd26];
        p_Result_92_reg_4310 <= add_ln1393_18_fu_2158_p2[32'd22];
        p_Result_93_reg_4320 <= p_Val2_89_fu_2201_p2[32'd15];
        p_Result_94_reg_4348 <= ret_V_9_fu_2278_p2[32'd26];
        p_Result_95_reg_4354 <= add_ln1393_20_fu_2290_p2[32'd22];
        p_Result_96_reg_4364 <= p_Val2_92_fu_2333_p2[32'd15];
        p_Val2_65_reg_3963 <= p_Val2_65_fu_1145_p2;
        p_Val2_68_reg_4007 <= p_Val2_68_fu_1277_p2;
        p_Val2_71_reg_4051 <= p_Val2_71_fu_1409_p2;
        p_Val2_74_reg_4095 <= p_Val2_74_fu_1541_p2;
        p_Val2_77_reg_4139 <= p_Val2_77_fu_1673_p2;
        p_Val2_80_reg_4183 <= p_Val2_80_fu_1805_p2;
        p_Val2_83_reg_4227 <= p_Val2_83_fu_1937_p2;
        p_Val2_86_reg_4271 <= p_Val2_86_fu_2069_p2;
        p_Val2_89_reg_4315 <= p_Val2_89_fu_2201_p2;
        p_Val2_92_reg_4359 <= p_Val2_92_fu_2333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln271_reg_3782 <= icmp_ln271_fu_531_p2;
        icmp_ln271_reg_3782_pp0_iter1_reg <= icmp_ln271_reg_3782;
        p_Result_65_reg_3818 <= inputs_q0[32'd30];
        p_Result_s_reg_3805 <= inputs_q0[32'd31];
        tmp_66_reg_3824 <= inputs_q0[32'd14];
        tmp_in_V_reg_3813 <= {{inputs_q0[30:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_531_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln271_reg_3786[6 : 0] <= zext_ln271_fu_543_p1[6 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln271_fu_531_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_cii_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_cii_1 = cii_fu_196;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_10_load_1 = buf_V_5_fu_3050_p3;
    end else begin
        ap_sig_allocacmp_lhs_10_load_1 = lhs_10_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_12_load_1 = buf_V_6_fu_3162_p3;
    end else begin
        ap_sig_allocacmp_lhs_12_load_1 = lhs_12_fu_180;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_14_load_1 = buf_V_7_fu_3274_p3;
    end else begin
        ap_sig_allocacmp_lhs_14_load_1 = lhs_14_fu_184;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_16_load_1 = buf_V_8_fu_3386_p3;
    end else begin
        ap_sig_allocacmp_lhs_16_load_1 = lhs_16_fu_188;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_18_load_1 = buf_V_9_fu_3498_p3;
    end else begin
        ap_sig_allocacmp_lhs_18_load_1 = lhs_18_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_2_load_1 = buf_V_1_fu_2602_p3;
    end else begin
        ap_sig_allocacmp_lhs_2_load_1 = lhs_2_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_4_load_1 = buf_V_2_fu_2714_p3;
    end else begin
        ap_sig_allocacmp_lhs_4_load_1 = lhs_4_fu_164;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_6_load_1 = buf_V_3_fu_2826_p3;
    end else begin
        ap_sig_allocacmp_lhs_6_load_1 = lhs_6_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_8_load_1 = buf_V_4_fu_2938_p3;
    end else begin
        ap_sig_allocacmp_lhs_8_load_1 = lhs_8_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_lhs_load_1 = buf_V_fu_2490_p3;
    end else begin
        ap_sig_allocacmp_lhs_load_1 = lhs_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputs_ce0 = 1'b1;
    end else begin
        inputs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_10_out_ap_vld = 1'b1;
    end else begin
        lhs_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_12_out_ap_vld = 1'b1;
    end else begin
        lhs_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_14_out_ap_vld = 1'b1;
    end else begin
        lhs_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_16_out_ap_vld = 1'b1;
    end else begin
        lhs_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_18_out_ap_vld = 1'b1;
    end else begin
        lhs_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_2_out_ap_vld = 1'b1;
    end else begin
        lhs_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_4_out_ap_vld = 1'b1;
    end else begin
        lhs_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_6_out_ap_vld = 1'b1;
    end else begin
        lhs_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_8_out_ap_vld = 1'b1;
    end else begin
        lhs_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_3782_pp0_iter4_reg == 1'd1))) begin
        lhs_out_ap_vld = 1'b1;
    end else begin
        lhs_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_0_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_1_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_2_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_3_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_4_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_5_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_6_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_7_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_8_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL17linear_weight_fix_9_ce0 = 1'b1;
    end else begin
        p_ZL17linear_weight_fix_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_10_fu_2373_p2 = ((tmp_18_fu_2363_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_1_fu_1185_p2 = ((tmp_1_fu_1175_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_2_fu_1317_p2 = ((tmp_3_fu_1307_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_3_fu_1449_p2 = ((tmp_5_fu_1439_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_4_fu_1581_p2 = ((tmp_7_fu_1571_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_5_fu_1713_p2 = ((tmp_9_fu_1703_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_6_fu_1845_p2 = ((tmp_11_fu_1835_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_7_fu_1977_p2 = ((tmp_13_fu_1967_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_8_fu_2109_p2 = ((tmp_15_fu_2099_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_ones_9_fu_2241_p2 = ((tmp_16_fu_2231_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_zeros_10_fu_2379_p2 = ((tmp_18_fu_2363_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_1_fu_1191_p2 = ((tmp_1_fu_1175_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_2_fu_1323_p2 = ((tmp_3_fu_1307_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_3_fu_1455_p2 = ((tmp_5_fu_1439_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_4_fu_1587_p2 = ((tmp_7_fu_1571_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_5_fu_1719_p2 = ((tmp_9_fu_1703_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_6_fu_1851_p2 = ((tmp_11_fu_1835_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_7_fu_1983_p2 = ((tmp_13_fu_1967_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_8_fu_2115_p2 = ((tmp_15_fu_2099_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_9_fu_2247_p2 = ((tmp_16_fu_2231_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_614_p2 = (p_Result_s_reg_3805 ^ 1'd1);

assign Range2_all_ones_1_fu_1301_p2 = ((tmp_2_fu_1291_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_2_fu_1433_p2 = ((tmp_4_fu_1423_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_3_fu_1565_p2 = ((tmp_6_fu_1555_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_4_fu_1697_p2 = ((tmp_8_fu_1687_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_5_fu_1829_p2 = ((tmp_10_fu_1819_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_6_fu_1961_p2 = ((tmp_12_fu_1951_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_7_fu_2093_p2 = ((tmp_14_fu_2083_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_8_fu_2225_p2 = ((tmp_s_fu_2215_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_9_fu_2357_p2 = ((tmp_17_fu_2347_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_1169_p2 = ((tmp_fu_1159_p4 == 3'd7) ? 1'b1 : 1'b0);

assign add_ln1393_10_fu_1630_p2 = ($signed(lhs_9_fu_1593_p3) + $signed(trunc_ln1393_8_fu_1608_p1));

assign add_ln1393_11_fu_1756_p2 = ($signed(sext_ln1393_11_fu_1746_p1) + $signed(trunc_ln1393_11_fu_1743_p1));

assign add_ln1393_12_fu_1762_p2 = ($signed(lhs_20_fu_1725_p3) + $signed(trunc_ln1393_10_fu_1740_p1));

assign add_ln1393_13_fu_1888_p2 = ($signed(sext_ln1393_13_fu_1878_p1) + $signed(trunc_ln1393_13_fu_1875_p1));

assign add_ln1393_14_fu_1894_p2 = ($signed(lhs_21_fu_1857_p3) + $signed(trunc_ln1393_12_fu_1872_p1));

assign add_ln1393_15_fu_2020_p2 = ($signed(sext_ln1393_15_fu_2010_p1) + $signed(trunc_ln1393_15_fu_2007_p1));

assign add_ln1393_16_fu_2026_p2 = ($signed(lhs_22_fu_1989_p3) + $signed(trunc_ln1393_14_fu_2004_p1));

assign add_ln1393_17_fu_2152_p2 = ($signed(sext_ln1393_17_fu_2142_p1) + $signed(trunc_ln1393_17_fu_2139_p1));

assign add_ln1393_18_fu_2158_p2 = ($signed(lhs_23_fu_2121_p3) + $signed(trunc_ln1393_16_fu_2136_p1));

assign add_ln1393_19_fu_2284_p2 = ($signed(sext_ln1393_19_fu_2274_p1) + $signed(trunc_ln1393_19_fu_2271_p1));

assign add_ln1393_1_fu_1096_p2 = ($signed(sext_ln1393_1_fu_1086_p1) + $signed(trunc_ln1393_1_fu_1083_p1));

assign add_ln1393_20_fu_2290_p2 = ($signed(lhs_24_fu_2253_p3) + $signed(trunc_ln1393_18_fu_2268_p1));

assign add_ln1393_2_fu_1102_p2 = ($signed(lhs_1_fu_1065_p3) + $signed(trunc_ln1393_fu_1080_p1));

assign add_ln1393_3_fu_1228_p2 = ($signed(sext_ln1393_3_fu_1218_p1) + $signed(trunc_ln1393_3_fu_1215_p1));

assign add_ln1393_4_fu_1234_p2 = ($signed(lhs_3_fu_1197_p3) + $signed(trunc_ln1393_2_fu_1212_p1));

assign add_ln1393_5_fu_1360_p2 = ($signed(sext_ln1393_5_fu_1350_p1) + $signed(trunc_ln1393_5_fu_1347_p1));

assign add_ln1393_6_fu_1366_p2 = ($signed(lhs_5_fu_1329_p3) + $signed(trunc_ln1393_4_fu_1344_p1));

assign add_ln1393_7_fu_1492_p2 = ($signed(sext_ln1393_7_fu_1482_p1) + $signed(trunc_ln1393_7_fu_1479_p1));

assign add_ln1393_8_fu_1498_p2 = ($signed(lhs_7_fu_1461_p3) + $signed(trunc_ln1393_6_fu_1476_p1));

assign add_ln1393_9_fu_1624_p2 = ($signed(sext_ln1393_9_fu_1614_p1) + $signed(trunc_ln1393_9_fu_1611_p1));

assign add_ln271_fu_537_p2 = (ap_sig_allocacmp_cii_1 + 7'd1);

assign and_ln936_1_fu_2526_p2 = (xor_ln936_1_fu_2520_p2 & Range2_all_ones_1_reg_4018);

assign and_ln936_2_fu_2638_p2 = (xor_ln936_2_fu_2632_p2 & Range2_all_ones_2_reg_4062);

assign and_ln936_3_fu_2750_p2 = (xor_ln936_3_fu_2744_p2 & Range2_all_ones_3_reg_4106);

assign and_ln936_4_fu_2862_p2 = (xor_ln936_4_fu_2856_p2 & Range2_all_ones_4_reg_4150);

assign and_ln936_5_fu_2974_p2 = (xor_ln936_5_fu_2968_p2 & Range2_all_ones_5_reg_4194);

assign and_ln936_6_fu_3086_p2 = (xor_ln936_6_fu_3080_p2 & Range2_all_ones_6_reg_4238);

assign and_ln936_7_fu_3198_p2 = (xor_ln936_7_fu_3192_p2 & Range2_all_ones_7_reg_4282);

assign and_ln936_8_fu_3310_p2 = (xor_ln936_8_fu_3304_p2 & Range2_all_ones_8_reg_4326);

assign and_ln936_9_fu_3422_p2 = (xor_ln936_9_fu_3416_p2 & Range2_all_ones_9_reg_4370);

assign and_ln936_fu_2414_p2 = (xor_ln936_fu_2408_p2 & Range2_all_ones_reg_3974);

assign and_ln937_1_fu_2538_p2 = (carry_5_fu_2502_p2 & Range1_all_ones_2_reg_4023);

assign and_ln937_2_fu_2650_p2 = (carry_7_fu_2614_p2 & Range1_all_ones_3_reg_4067);

assign and_ln937_3_fu_2762_p2 = (carry_9_fu_2726_p2 & Range1_all_ones_4_reg_4111);

assign and_ln937_4_fu_2874_p2 = (carry_11_fu_2838_p2 & Range1_all_ones_5_reg_4155);

assign and_ln937_5_fu_2986_p2 = (carry_13_fu_2950_p2 & Range1_all_ones_6_reg_4199);

assign and_ln937_6_fu_3098_p2 = (carry_15_fu_3062_p2 & Range1_all_ones_7_reg_4243);

assign and_ln937_7_fu_3210_p2 = (carry_17_fu_3174_p2 & Range1_all_ones_8_reg_4287);

assign and_ln937_8_fu_3322_p2 = (carry_19_fu_3286_p2 & Range1_all_ones_9_reg_4331);

assign and_ln937_9_fu_3434_p2 = (carry_21_fu_3398_p2 & Range1_all_ones_10_reg_4375);

assign and_ln937_fu_2426_p2 = (carry_3_fu_2390_p2 & Range1_all_ones_1_reg_3979);

assign and_ln942_fu_674_p2 = (p_Result_s_reg_3805 & or_ln937_fu_638_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_V_1_fu_2602_p3 = ((or_ln392_2_fu_2596_p2[0:0] == 1'b1) ? select_ln392_4_fu_2588_p3 : p_Val2_68_reg_4007);

assign buf_V_2_fu_2714_p3 = ((or_ln392_3_fu_2708_p2[0:0] == 1'b1) ? select_ln392_6_fu_2700_p3 : p_Val2_71_reg_4051);

assign buf_V_3_fu_2826_p3 = ((or_ln392_4_fu_2820_p2[0:0] == 1'b1) ? select_ln392_8_fu_2812_p3 : p_Val2_74_reg_4095);

assign buf_V_4_fu_2938_p3 = ((or_ln392_5_fu_2932_p2[0:0] == 1'b1) ? select_ln392_10_fu_2924_p3 : p_Val2_77_reg_4139);

assign buf_V_5_fu_3050_p3 = ((or_ln392_6_fu_3044_p2[0:0] == 1'b1) ? select_ln392_12_fu_3036_p3 : p_Val2_80_reg_4183);

assign buf_V_6_fu_3162_p3 = ((or_ln392_7_fu_3156_p2[0:0] == 1'b1) ? select_ln392_14_fu_3148_p3 : p_Val2_83_reg_4227);

assign buf_V_7_fu_3274_p3 = ((or_ln392_8_fu_3268_p2[0:0] == 1'b1) ? select_ln392_16_fu_3260_p3 : p_Val2_86_reg_4271);

assign buf_V_8_fu_3386_p3 = ((or_ln392_9_fu_3380_p2[0:0] == 1'b1) ? select_ln392_18_fu_3372_p3 : p_Val2_89_reg_4315);

assign buf_V_9_fu_3498_p3 = ((or_ln392_10_fu_3492_p2[0:0] == 1'b1) ? select_ln392_20_fu_3484_p3 : p_Val2_92_reg_4359);

assign buf_V_fu_2490_p3 = ((or_ln392_1_fu_2484_p2[0:0] == 1'b1) ? select_ln392_fu_2476_p3 : p_Val2_65_reg_3963);

assign carry_11_fu_2838_p2 = (xor_ln942_10_fu_2833_p2 & p_Result_80_reg_4134);

assign carry_13_fu_2950_p2 = (xor_ln942_12_fu_2945_p2 & p_Result_83_reg_4178);

assign carry_15_fu_3062_p2 = (xor_ln942_14_fu_3057_p2 & p_Result_86_reg_4222);

assign carry_17_fu_3174_p2 = (xor_ln942_16_fu_3169_p2 & p_Result_89_reg_4266);

assign carry_19_fu_3286_p2 = (xor_ln942_18_fu_3281_p2 & p_Result_92_reg_4310);

assign carry_1_fu_609_p2 = (xor_ln942_fu_603_p2 & p_Result_65_reg_3818);

assign carry_21_fu_3398_p2 = (xor_ln942_20_fu_3393_p2 & p_Result_95_reg_4354);

assign carry_3_fu_2390_p2 = (xor_ln942_2_fu_2385_p2 & p_Result_68_reg_3958);

assign carry_5_fu_2502_p2 = (xor_ln942_4_fu_2497_p2 & p_Result_71_reg_4002);

assign carry_7_fu_2614_p2 = (xor_ln942_6_fu_2609_p2 & p_Result_74_reg_4046);

assign carry_9_fu_2726_p2 = (xor_ln942_8_fu_2721_p2 & p_Result_77_reg_4090);

assign deleted_ones_10_fu_3427_p3 = ((carry_21_fu_3398_p2[0:0] == 1'b1) ? and_ln936_9_fu_3422_p2 : Range1_all_ones_10_reg_4375);

assign deleted_ones_1_fu_2419_p3 = ((carry_3_fu_2390_p2[0:0] == 1'b1) ? and_ln936_fu_2414_p2 : Range1_all_ones_1_reg_3979);

assign deleted_ones_2_fu_2531_p3 = ((carry_5_fu_2502_p2[0:0] == 1'b1) ? and_ln936_1_fu_2526_p2 : Range1_all_ones_2_reg_4023);

assign deleted_ones_3_fu_2643_p3 = ((carry_7_fu_2614_p2[0:0] == 1'b1) ? and_ln936_2_fu_2638_p2 : Range1_all_ones_3_reg_4067);

assign deleted_ones_4_fu_2755_p3 = ((carry_9_fu_2726_p2[0:0] == 1'b1) ? and_ln936_3_fu_2750_p2 : Range1_all_ones_4_reg_4111);

assign deleted_ones_5_fu_2867_p3 = ((carry_11_fu_2838_p2[0:0] == 1'b1) ? and_ln936_4_fu_2862_p2 : Range1_all_ones_5_reg_4155);

assign deleted_ones_6_fu_2979_p3 = ((carry_13_fu_2950_p2[0:0] == 1'b1) ? and_ln936_5_fu_2974_p2 : Range1_all_ones_6_reg_4199);

assign deleted_ones_7_fu_3091_p3 = ((carry_15_fu_3062_p2[0:0] == 1'b1) ? and_ln936_6_fu_3086_p2 : Range1_all_ones_7_reg_4243);

assign deleted_ones_8_fu_3203_p3 = ((carry_17_fu_3174_p2[0:0] == 1'b1) ? and_ln936_7_fu_3198_p2 : Range1_all_ones_8_reg_4287);

assign deleted_ones_9_fu_3315_p3 = ((carry_19_fu_3286_p2[0:0] == 1'b1) ? and_ln936_8_fu_3310_p2 : Range1_all_ones_9_reg_4331);

assign deleted_ones_fu_626_p3 = ((carry_1_fu_609_p2[0:0] == 1'b1) ? Range1_all_zeros_fu_614_p2 : p_Result_s_reg_3805);

assign deleted_zeros_10_fu_3403_p3 = ((carry_21_fu_3398_p2[0:0] == 1'b1) ? Range1_all_ones_10_reg_4375 : Range1_all_zeros_10_reg_4382);

assign deleted_zeros_1_fu_2395_p3 = ((carry_3_fu_2390_p2[0:0] == 1'b1) ? Range1_all_ones_1_reg_3979 : Range1_all_zeros_1_reg_3986);

assign deleted_zeros_2_fu_2507_p3 = ((carry_5_fu_2502_p2[0:0] == 1'b1) ? Range1_all_ones_2_reg_4023 : Range1_all_zeros_2_reg_4030);

assign deleted_zeros_3_fu_2619_p3 = ((carry_7_fu_2614_p2[0:0] == 1'b1) ? Range1_all_ones_3_reg_4067 : Range1_all_zeros_3_reg_4074);

assign deleted_zeros_4_fu_2731_p3 = ((carry_9_fu_2726_p2[0:0] == 1'b1) ? Range1_all_ones_4_reg_4111 : Range1_all_zeros_4_reg_4118);

assign deleted_zeros_5_fu_2843_p3 = ((carry_11_fu_2838_p2[0:0] == 1'b1) ? Range1_all_ones_5_reg_4155 : Range1_all_zeros_5_reg_4162);

assign deleted_zeros_6_fu_2955_p3 = ((carry_13_fu_2950_p2[0:0] == 1'b1) ? Range1_all_ones_6_reg_4199 : Range1_all_zeros_6_reg_4206);

assign deleted_zeros_7_fu_3067_p3 = ((carry_15_fu_3062_p2[0:0] == 1'b1) ? Range1_all_ones_7_reg_4243 : Range1_all_zeros_7_reg_4250);

assign deleted_zeros_8_fu_3179_p3 = ((carry_17_fu_3174_p2[0:0] == 1'b1) ? Range1_all_ones_8_reg_4287 : Range1_all_zeros_8_reg_4294);

assign deleted_zeros_9_fu_3291_p3 = ((carry_19_fu_3286_p2[0:0] == 1'b1) ? Range1_all_ones_9_reg_4331 : Range1_all_zeros_9_reg_4338);

assign deleted_zeros_fu_619_p3 = ((carry_1_fu_609_p2[0:0] == 1'b1) ? p_Result_s_reg_3805 : Range1_all_zeros_fu_614_p2);

assign grp_fu_3595_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3605_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3615_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3635_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3645_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3655_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3665_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3675_p1 = sext_ln1316_1_fu_991_p1;

assign grp_fu_3685_p1 = sext_ln1316_1_fu_991_p1;

assign icmp_ln271_fu_531_p2 = ((ap_sig_allocacmp_cii_1 == 7'd64) ? 1'b1 : 1'b0);

assign inputs_address0 = zext_ln271_fu_543_p1;

assign lhs_10_out = lhs_10_fu_176;

assign lhs_12_out = lhs_12_fu_180;

assign lhs_14_out = lhs_14_fu_184;

assign lhs_16_out = lhs_16_fu_188;

assign lhs_18_out = lhs_18_fu_192;

assign lhs_1_fu_1065_p3 = {{ap_sig_allocacmp_lhs_load_1}, {7'd0}};

assign lhs_20_fu_1725_p3 = {{ap_sig_allocacmp_lhs_10_load_1}, {7'd0}};

assign lhs_21_fu_1857_p3 = {{ap_sig_allocacmp_lhs_12_load_1}, {7'd0}};

assign lhs_22_fu_1989_p3 = {{ap_sig_allocacmp_lhs_14_load_1}, {7'd0}};

assign lhs_23_fu_2121_p3 = {{ap_sig_allocacmp_lhs_16_load_1}, {7'd0}};

assign lhs_24_fu_2253_p3 = {{ap_sig_allocacmp_lhs_18_load_1}, {7'd0}};

assign lhs_2_out = lhs_2_fu_160;

assign lhs_3_fu_1197_p3 = {{ap_sig_allocacmp_lhs_2_load_1}, {7'd0}};

assign lhs_4_out = lhs_4_fu_164;

assign lhs_5_fu_1329_p3 = {{ap_sig_allocacmp_lhs_4_load_1}, {7'd0}};

assign lhs_6_out = lhs_6_fu_168;

assign lhs_7_fu_1461_p3 = {{ap_sig_allocacmp_lhs_6_load_1}, {7'd0}};

assign lhs_8_out = lhs_8_fu_172;

assign lhs_9_fu_1593_p3 = {{ap_sig_allocacmp_lhs_8_load_1}, {7'd0}};

assign lhs_out = lhs_fu_156;

assign or_ln392_10_fu_3492_p2 = (underflow_10_fu_3479_p2 | overflow_10_fu_3455_p2);

assign or_ln392_1_fu_2484_p2 = (underflow_1_fu_2471_p2 | overflow_1_fu_2447_p2);

assign or_ln392_2_fu_2596_p2 = (underflow_2_fu_2583_p2 | overflow_2_fu_2559_p2);

assign or_ln392_3_fu_2708_p2 = (underflow_3_fu_2695_p2 | overflow_3_fu_2671_p2);

assign or_ln392_4_fu_2820_p2 = (underflow_4_fu_2807_p2 | overflow_4_fu_2783_p2);

assign or_ln392_5_fu_2932_p2 = (underflow_5_fu_2919_p2 | overflow_5_fu_2895_p2);

assign or_ln392_6_fu_3044_p2 = (underflow_6_fu_3031_p2 | overflow_6_fu_3007_p2);

assign or_ln392_7_fu_3156_p2 = (underflow_7_fu_3143_p2 | overflow_7_fu_3119_p2);

assign or_ln392_8_fu_3268_p2 = (underflow_8_fu_3255_p2 | overflow_8_fu_3231_p2);

assign or_ln392_9_fu_3380_p2 = (underflow_9_fu_3367_p2 | overflow_9_fu_3343_p2);

assign or_ln392_fu_693_p2 = (underflow_fu_679_p2 | overflow_fu_656_p2);

assign or_ln937_fu_638_p2 = (xor_ln937_fu_633_p2 | p_Result_66_fu_595_p3);

assign or_ln941_10_fu_3445_p2 = (xor_ln941_19_fu_3439_p2 | p_Result_96_reg_4364);

assign or_ln941_1_fu_2437_p2 = (xor_ln941_1_fu_2431_p2 | p_Result_69_reg_3968);

assign or_ln941_2_fu_2549_p2 = (xor_ln941_3_fu_2543_p2 | p_Result_72_reg_4012);

assign or_ln941_3_fu_2661_p2 = (xor_ln941_5_fu_2655_p2 | p_Result_75_reg_4056);

assign or_ln941_4_fu_2773_p2 = (xor_ln941_7_fu_2767_p2 | p_Result_78_reg_4100);

assign or_ln941_5_fu_2885_p2 = (xor_ln941_9_fu_2879_p2 | p_Result_81_reg_4144);

assign or_ln941_6_fu_2997_p2 = (xor_ln941_11_fu_2991_p2 | p_Result_84_reg_4188);

assign or_ln941_7_fu_3109_p2 = (xor_ln941_13_fu_3103_p2 | p_Result_87_reg_4232);

assign or_ln941_8_fu_3221_p2 = (xor_ln941_15_fu_3215_p2 | p_Result_90_reg_4276);

assign or_ln941_9_fu_3333_p2 = (xor_ln941_17_fu_3327_p2 | p_Result_93_reg_4320);

assign or_ln941_fu_650_p2 = (xor_ln941_fu_644_p2 | p_Result_66_fu_595_p3);

assign or_ln942_10_fu_3467_p2 = (xor_ln942_21_fu_3461_p2 | xor_ln942_20_fu_3393_p2);

assign or_ln942_1_fu_2459_p2 = (xor_ln942_3_fu_2453_p2 | xor_ln942_2_fu_2385_p2);

assign or_ln942_2_fu_2571_p2 = (xor_ln942_5_fu_2565_p2 | xor_ln942_4_fu_2497_p2);

assign or_ln942_3_fu_2683_p2 = (xor_ln942_7_fu_2677_p2 | xor_ln942_6_fu_2609_p2);

assign or_ln942_4_fu_2795_p2 = (xor_ln942_9_fu_2789_p2 | xor_ln942_8_fu_2721_p2);

assign or_ln942_5_fu_2907_p2 = (xor_ln942_11_fu_2901_p2 | xor_ln942_10_fu_2833_p2);

assign or_ln942_6_fu_3019_p2 = (xor_ln942_13_fu_3013_p2 | xor_ln942_12_fu_2945_p2);

assign or_ln942_7_fu_3131_p2 = (xor_ln942_15_fu_3125_p2 | xor_ln942_14_fu_3057_p2);

assign or_ln942_8_fu_3243_p2 = (xor_ln942_17_fu_3237_p2 | xor_ln942_16_fu_3169_p2);

assign or_ln942_9_fu_3355_p2 = (xor_ln942_19_fu_3349_p2 | xor_ln942_18_fu_3281_p2);

assign or_ln942_fu_668_p2 = (xor_ln942_fu_603_p2 | xor_ln942_1_fu_662_p2);

assign overflow_10_fu_3455_p2 = (xor_ln941_20_fu_3450_p2 & or_ln941_10_fu_3445_p2);

assign overflow_1_fu_2447_p2 = (xor_ln941_2_fu_2442_p2 & or_ln941_1_fu_2437_p2);

assign overflow_2_fu_2559_p2 = (xor_ln941_4_fu_2554_p2 & or_ln941_2_fu_2549_p2);

assign overflow_3_fu_2671_p2 = (xor_ln941_6_fu_2666_p2 & or_ln941_3_fu_2661_p2);

assign overflow_4_fu_2783_p2 = (xor_ln941_8_fu_2778_p2 & or_ln941_4_fu_2773_p2);

assign overflow_5_fu_2895_p2 = (xor_ln941_10_fu_2890_p2 & or_ln941_5_fu_2885_p2);

assign overflow_6_fu_3007_p2 = (xor_ln941_12_fu_3002_p2 & or_ln941_6_fu_2997_p2);

assign overflow_7_fu_3119_p2 = (xor_ln941_14_fu_3114_p2 & or_ln941_7_fu_3109_p2);

assign overflow_8_fu_3231_p2 = (xor_ln941_16_fu_3226_p2 & or_ln941_8_fu_3221_p2);

assign overflow_9_fu_3343_p2 = (xor_ln941_18_fu_3338_p2 & or_ln941_9_fu_3333_p2);

assign overflow_fu_656_p2 = (or_ln941_fu_650_p2 & Range1_all_zeros_fu_614_p2);

assign p_Result_66_fu_595_p3 = tmp_in_V_1_fu_590_p2[32'd15];

assign p_Val2_64_fu_1116_p4 = {{add_ln1393_2_fu_1102_p2[22:7]}};

assign p_Val2_65_fu_1145_p2 = (zext_ln423_11_fu_1141_p1 + p_Val2_64_fu_1116_p4);

assign p_Val2_67_fu_1248_p4 = {{add_ln1393_4_fu_1234_p2[22:7]}};

assign p_Val2_68_fu_1277_p2 = (zext_ln423_12_fu_1273_p1 + p_Val2_67_fu_1248_p4);

assign p_Val2_70_fu_1380_p4 = {{add_ln1393_6_fu_1366_p2[22:7]}};

assign p_Val2_71_fu_1409_p2 = (zext_ln423_13_fu_1405_p1 + p_Val2_70_fu_1380_p4);

assign p_Val2_73_fu_1512_p4 = {{add_ln1393_8_fu_1498_p2[22:7]}};

assign p_Val2_74_fu_1541_p2 = (zext_ln423_14_fu_1537_p1 + p_Val2_73_fu_1512_p4);

assign p_Val2_76_fu_1644_p4 = {{add_ln1393_10_fu_1630_p2[22:7]}};

assign p_Val2_77_fu_1673_p2 = (zext_ln423_15_fu_1669_p1 + p_Val2_76_fu_1644_p4);

assign p_Val2_79_fu_1776_p4 = {{add_ln1393_12_fu_1762_p2[22:7]}};

assign p_Val2_80_fu_1805_p2 = (zext_ln423_16_fu_1801_p1 + p_Val2_79_fu_1776_p4);

assign p_Val2_82_fu_1908_p4 = {{add_ln1393_14_fu_1894_p2[22:7]}};

assign p_Val2_83_fu_1937_p2 = (zext_ln423_17_fu_1933_p1 + p_Val2_82_fu_1908_p4);

assign p_Val2_85_fu_2040_p4 = {{add_ln1393_16_fu_2026_p2[22:7]}};

assign p_Val2_86_fu_2069_p2 = (zext_ln423_18_fu_2065_p1 + p_Val2_85_fu_2040_p4);

assign p_Val2_88_fu_2172_p4 = {{add_ln1393_18_fu_2158_p2[22:7]}};

assign p_Val2_89_fu_2201_p2 = (zext_ln423_19_fu_2197_p1 + p_Val2_88_fu_2172_p4);

assign p_Val2_91_fu_2304_p4 = {{add_ln1393_20_fu_2290_p2[22:7]}};

assign p_Val2_92_fu_2333_p2 = (zext_ln423_20_fu_2329_p1 + p_Val2_91_fu_2304_p4);

assign p_ZL17linear_weight_fix_0_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_1_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_2_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_3_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_4_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_5_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_6_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_7_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_8_address0 = zext_ln271_reg_3786;

assign p_ZL17linear_weight_fix_9_address0 = zext_ln271_reg_3786;

assign ret_V_1_fu_1222_p2 = ($signed(sext_ln1393_2_fu_1205_p1) + $signed(sext_ln1393_21_fu_1209_p1));

assign ret_V_2_fu_1354_p2 = ($signed(sext_ln1393_4_fu_1337_p1) + $signed(sext_ln1393_22_fu_1341_p1));

assign ret_V_3_fu_1486_p2 = ($signed(sext_ln1393_6_fu_1469_p1) + $signed(sext_ln1393_23_fu_1473_p1));

assign ret_V_4_fu_1618_p2 = ($signed(sext_ln1393_8_fu_1601_p1) + $signed(sext_ln1393_24_fu_1605_p1));

assign ret_V_5_fu_1750_p2 = ($signed(sext_ln1393_10_fu_1733_p1) + $signed(sext_ln1393_25_fu_1737_p1));

assign ret_V_6_fu_1882_p2 = ($signed(sext_ln1393_12_fu_1865_p1) + $signed(sext_ln1393_26_fu_1869_p1));

assign ret_V_7_fu_2014_p2 = ($signed(sext_ln1393_14_fu_1997_p1) + $signed(sext_ln1393_27_fu_2001_p1));

assign ret_V_8_fu_2146_p2 = ($signed(sext_ln1393_16_fu_2129_p1) + $signed(sext_ln1393_28_fu_2133_p1));

assign ret_V_9_fu_2278_p2 = ($signed(sext_ln1393_18_fu_2261_p1) + $signed(sext_ln1393_29_fu_2265_p1));

assign ret_V_fu_1090_p2 = ($signed(sext_ln1393_fu_1073_p1) + $signed(sext_ln1393_20_fu_1077_p1));

assign select_ln392_10_fu_2924_p3 = ((overflow_5_fu_2895_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_12_fu_3036_p3 = ((overflow_6_fu_3007_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_14_fu_3148_p3 = ((overflow_7_fu_3119_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_16_fu_3260_p3 = ((overflow_8_fu_3231_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_18_fu_3372_p3 = ((overflow_9_fu_3343_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_1_fu_685_p3 = ((overflow_fu_656_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_20_fu_3484_p3 = ((overflow_10_fu_3455_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_4_fu_2588_p3 = ((overflow_2_fu_2559_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_6_fu_2700_p3 = ((overflow_3_fu_2671_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_8_fu_2812_p3 = ((overflow_4_fu_2783_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln392_fu_2476_p3 = ((overflow_1_fu_2447_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln1316_1_fu_991_p1 = tmp_in_V_2_fu_699_p3;

assign sext_ln1393_10_fu_1733_p1 = lhs_20_fu_1725_p3;

assign sext_ln1393_11_fu_1746_p1 = lhs_20_fu_1725_p3;

assign sext_ln1393_12_fu_1865_p1 = lhs_21_fu_1857_p3;

assign sext_ln1393_13_fu_1878_p1 = lhs_21_fu_1857_p3;

assign sext_ln1393_14_fu_1997_p1 = lhs_22_fu_1989_p3;

assign sext_ln1393_15_fu_2010_p1 = lhs_22_fu_1989_p3;

assign sext_ln1393_16_fu_2129_p1 = lhs_23_fu_2121_p3;

assign sext_ln1393_17_fu_2142_p1 = lhs_23_fu_2121_p3;

assign sext_ln1393_18_fu_2261_p1 = lhs_24_fu_2253_p3;

assign sext_ln1393_19_fu_2274_p1 = lhs_24_fu_2253_p3;

assign sext_ln1393_1_fu_1086_p1 = lhs_1_fu_1065_p3;

assign sext_ln1393_20_fu_1077_p1 = grp_fu_3595_p2;

assign sext_ln1393_21_fu_1209_p1 = grp_fu_3605_p2;

assign sext_ln1393_22_fu_1341_p1 = grp_fu_3615_p2;

assign sext_ln1393_23_fu_1473_p1 = grp_fu_3625_p2;

assign sext_ln1393_24_fu_1605_p1 = grp_fu_3635_p2;

assign sext_ln1393_25_fu_1737_p1 = grp_fu_3645_p2;

assign sext_ln1393_26_fu_1869_p1 = grp_fu_3655_p2;

assign sext_ln1393_27_fu_2001_p1 = grp_fu_3665_p2;

assign sext_ln1393_28_fu_2133_p1 = grp_fu_3675_p2;

assign sext_ln1393_29_fu_2265_p1 = grp_fu_3685_p2;

assign sext_ln1393_2_fu_1205_p1 = lhs_3_fu_1197_p3;

assign sext_ln1393_3_fu_1218_p1 = lhs_3_fu_1197_p3;

assign sext_ln1393_4_fu_1337_p1 = lhs_5_fu_1329_p3;

assign sext_ln1393_5_fu_1350_p1 = lhs_5_fu_1329_p3;

assign sext_ln1393_6_fu_1469_p1 = lhs_7_fu_1461_p3;

assign sext_ln1393_7_fu_1482_p1 = lhs_7_fu_1461_p3;

assign sext_ln1393_8_fu_1601_p1 = lhs_9_fu_1593_p3;

assign sext_ln1393_9_fu_1614_p1 = lhs_9_fu_1593_p3;

assign sext_ln1393_fu_1073_p1 = lhs_1_fu_1065_p3;

assign sext_ln869_1_fu_749_p1 = $signed(trunc_ln864_4_fu_739_p4);

assign sext_ln869_2_fu_777_p1 = $signed(trunc_ln864_6_fu_767_p4);

assign sext_ln869_3_fu_805_p1 = $signed(trunc_ln864_8_fu_795_p4);

assign sext_ln869_4_fu_833_p1 = $signed(trunc_ln864_s_fu_823_p4);

assign sext_ln869_5_fu_861_p1 = $signed(trunc_ln864_10_fu_851_p4);

assign sext_ln869_6_fu_889_p1 = $signed(trunc_ln864_12_fu_879_p4);

assign sext_ln869_7_fu_917_p1 = $signed(trunc_ln864_14_fu_907_p4);

assign sext_ln869_8_fu_945_p1 = $signed(trunc_ln864_16_fu_935_p4);

assign sext_ln869_9_fu_973_p1 = $signed(trunc_ln864_18_fu_963_p4);

assign sext_ln869_fu_721_p1 = $signed(trunc_ln864_2_fu_711_p4);

assign tmp_100_fu_1926_p3 = grp_fu_3655_p2[32'd6];

assign tmp_102_fu_3073_p3 = add_ln1393_13_reg_4211[32'd23];

assign tmp_105_fu_2058_p3 = grp_fu_3665_p2[32'd6];

assign tmp_107_fu_3185_p3 = add_ln1393_15_reg_4255[32'd23];

assign tmp_10_fu_1819_p4 = {{ret_V_5_fu_1750_p2[26:24]}};

assign tmp_110_fu_2190_p3 = grp_fu_3675_p2[32'd6];

assign tmp_112_fu_3297_p3 = add_ln1393_17_reg_4299[32'd23];

assign tmp_115_fu_2322_p3 = grp_fu_3685_p2[32'd6];

assign tmp_117_fu_3409_p3 = add_ln1393_19_reg_4343[32'd23];

assign tmp_11_fu_1835_p4 = {{ret_V_5_fu_1750_p2[26:23]}};

assign tmp_12_fu_1951_p4 = {{ret_V_6_fu_1882_p2[26:24]}};

assign tmp_13_fu_1967_p4 = {{ret_V_6_fu_1882_p2[26:23]}};

assign tmp_14_fu_2083_p4 = {{ret_V_7_fu_2014_p2[26:24]}};

assign tmp_15_fu_2099_p4 = {{ret_V_7_fu_2014_p2[26:23]}};

assign tmp_16_fu_2231_p4 = {{ret_V_8_fu_2146_p2[26:23]}};

assign tmp_17_fu_2347_p4 = {{ret_V_9_fu_2278_p2[26:24]}};

assign tmp_18_fu_2363_p4 = {{ret_V_9_fu_2278_p2[26:23]}};

assign tmp_1_fu_1175_p4 = {{ret_V_fu_1090_p2[26:23]}};

assign tmp_2_fu_1291_p4 = {{ret_V_1_fu_1222_p2[26:24]}};

assign tmp_3_fu_1307_p4 = {{ret_V_1_fu_1222_p2[26:23]}};

assign tmp_4_fu_1423_p4 = {{ret_V_2_fu_1354_p2[26:24]}};

assign tmp_5_fu_1439_p4 = {{ret_V_2_fu_1354_p2[26:23]}};

assign tmp_6_fu_1555_p4 = {{ret_V_3_fu_1486_p2[26:24]}};

assign tmp_70_fu_1134_p3 = grp_fu_3595_p2[32'd6];

assign tmp_72_fu_2401_p3 = add_ln1393_1_reg_3947[32'd23];

assign tmp_75_fu_1266_p3 = grp_fu_3605_p2[32'd6];

assign tmp_77_fu_2513_p3 = add_ln1393_3_reg_3991[32'd23];

assign tmp_7_fu_1571_p4 = {{ret_V_3_fu_1486_p2[26:23]}};

assign tmp_80_fu_1398_p3 = grp_fu_3615_p2[32'd6];

assign tmp_82_fu_2625_p3 = add_ln1393_5_reg_4035[32'd23];

assign tmp_85_fu_1530_p3 = grp_fu_3625_p2[32'd6];

assign tmp_87_fu_2737_p3 = add_ln1393_7_reg_4079[32'd23];

assign tmp_8_fu_1687_p4 = {{ret_V_4_fu_1618_p2[26:24]}};

assign tmp_90_fu_1662_p3 = grp_fu_3635_p2[32'd6];

assign tmp_92_fu_2849_p3 = add_ln1393_9_reg_4123[32'd23];

assign tmp_95_fu_1794_p3 = grp_fu_3645_p2[32'd6];

assign tmp_97_fu_2961_p3 = add_ln1393_11_reg_4167[32'd23];

assign tmp_9_fu_1703_p4 = {{ret_V_4_fu_1618_p2[26:23]}};

assign tmp_fu_1159_p4 = {{ret_V_fu_1090_p2[26:24]}};

assign tmp_in_V_1_fu_590_p2 = (zext_ln423_fu_587_p1 + tmp_in_V_reg_3813);

assign tmp_in_V_2_fu_699_p3 = ((or_ln392_fu_693_p2[0:0] == 1'b1) ? select_ln392_1_fu_685_p3 : tmp_in_V_1_fu_590_p2);

assign tmp_s_fu_2215_p4 = {{ret_V_8_fu_2146_p2[26:24]}};

assign tmp_wt_V_1_fu_757_p2 = ($signed(zext_ln423_2_fu_753_p1) + $signed(sext_ln869_1_fu_749_p1));

assign tmp_wt_V_2_fu_785_p2 = ($signed(zext_ln423_3_fu_781_p1) + $signed(sext_ln869_2_fu_777_p1));

assign tmp_wt_V_3_fu_813_p2 = ($signed(zext_ln423_4_fu_809_p1) + $signed(sext_ln869_3_fu_805_p1));

assign tmp_wt_V_4_fu_841_p2 = ($signed(zext_ln423_5_fu_837_p1) + $signed(sext_ln869_4_fu_833_p1));

assign tmp_wt_V_5_fu_869_p2 = ($signed(zext_ln423_6_fu_865_p1) + $signed(sext_ln869_5_fu_861_p1));

assign tmp_wt_V_6_fu_897_p2 = ($signed(zext_ln423_7_fu_893_p1) + $signed(sext_ln869_6_fu_889_p1));

assign tmp_wt_V_7_fu_925_p2 = ($signed(zext_ln423_8_fu_921_p1) + $signed(sext_ln869_7_fu_917_p1));

assign tmp_wt_V_8_fu_953_p2 = ($signed(zext_ln423_9_fu_949_p1) + $signed(sext_ln869_8_fu_945_p1));

assign tmp_wt_V_9_fu_981_p2 = ($signed(zext_ln423_10_fu_977_p1) + $signed(sext_ln869_9_fu_973_p1));

assign tmp_wt_V_fu_729_p2 = ($signed(zext_ln423_1_fu_725_p1) + $signed(sext_ln869_fu_721_p1));

assign trunc_ln1393_10_fu_1740_p1 = grp_fu_3645_p2[22:0];

assign trunc_ln1393_11_fu_1743_p1 = grp_fu_3645_p2[23:0];

assign trunc_ln1393_12_fu_1872_p1 = grp_fu_3655_p2[22:0];

assign trunc_ln1393_13_fu_1875_p1 = grp_fu_3655_p2[23:0];

assign trunc_ln1393_14_fu_2004_p1 = grp_fu_3665_p2[22:0];

assign trunc_ln1393_15_fu_2007_p1 = grp_fu_3665_p2[23:0];

assign trunc_ln1393_16_fu_2136_p1 = grp_fu_3675_p2[22:0];

assign trunc_ln1393_17_fu_2139_p1 = grp_fu_3675_p2[23:0];

assign trunc_ln1393_18_fu_2268_p1 = grp_fu_3685_p2[22:0];

assign trunc_ln1393_19_fu_2271_p1 = grp_fu_3685_p2[23:0];

assign trunc_ln1393_1_fu_1083_p1 = grp_fu_3595_p2[23:0];

assign trunc_ln1393_2_fu_1212_p1 = grp_fu_3605_p2[22:0];

assign trunc_ln1393_3_fu_1215_p1 = grp_fu_3605_p2[23:0];

assign trunc_ln1393_4_fu_1344_p1 = grp_fu_3615_p2[22:0];

assign trunc_ln1393_5_fu_1347_p1 = grp_fu_3615_p2[23:0];

assign trunc_ln1393_6_fu_1476_p1 = grp_fu_3625_p2[22:0];

assign trunc_ln1393_7_fu_1479_p1 = grp_fu_3625_p2[23:0];

assign trunc_ln1393_8_fu_1608_p1 = grp_fu_3635_p2[22:0];

assign trunc_ln1393_9_fu_1611_p1 = grp_fu_3635_p2[23:0];

assign trunc_ln1393_fu_1080_p1 = grp_fu_3595_p2[22:0];

assign trunc_ln864_10_fu_851_p4 = {{p_ZL17linear_weight_fix_5_q0[9:1]}};

assign trunc_ln864_11_fu_875_p1 = p_ZL17linear_weight_fix_6_q0[0:0];

assign trunc_ln864_12_fu_879_p4 = {{p_ZL17linear_weight_fix_6_q0[9:1]}};

assign trunc_ln864_13_fu_903_p1 = p_ZL17linear_weight_fix_7_q0[0:0];

assign trunc_ln864_14_fu_907_p4 = {{p_ZL17linear_weight_fix_7_q0[9:1]}};

assign trunc_ln864_15_fu_931_p1 = p_ZL17linear_weight_fix_8_q0[0:0];

assign trunc_ln864_16_fu_935_p4 = {{p_ZL17linear_weight_fix_8_q0[9:1]}};

assign trunc_ln864_17_fu_959_p1 = p_ZL17linear_weight_fix_9_q0[0:0];

assign trunc_ln864_18_fu_963_p4 = {{p_ZL17linear_weight_fix_9_q0[9:1]}};

assign trunc_ln864_1_fu_735_p1 = p_ZL17linear_weight_fix_1_q0[0:0];

assign trunc_ln864_2_fu_711_p4 = {{p_ZL17linear_weight_fix_0_q0[9:1]}};

assign trunc_ln864_3_fu_763_p1 = p_ZL17linear_weight_fix_2_q0[0:0];

assign trunc_ln864_4_fu_739_p4 = {{p_ZL17linear_weight_fix_1_q0[9:1]}};

assign trunc_ln864_5_fu_791_p1 = p_ZL17linear_weight_fix_3_q0[0:0];

assign trunc_ln864_6_fu_767_p4 = {{p_ZL17linear_weight_fix_2_q0[9:1]}};

assign trunc_ln864_7_fu_819_p1 = p_ZL17linear_weight_fix_4_q0[0:0];

assign trunc_ln864_8_fu_795_p4 = {{p_ZL17linear_weight_fix_3_q0[8:1]}};

assign trunc_ln864_9_fu_847_p1 = p_ZL17linear_weight_fix_5_q0[0:0];

assign trunc_ln864_fu_707_p1 = p_ZL17linear_weight_fix_0_q0[0:0];

assign trunc_ln864_s_fu_823_p4 = {{p_ZL17linear_weight_fix_4_q0[9:1]}};

assign underflow_10_fu_3479_p2 = (xor_ln942_31_fu_3473_p2 & p_Result_94_reg_4348);

assign underflow_1_fu_2471_p2 = (xor_ln942_22_fu_2465_p2 & p_Result_67_reg_3952);

assign underflow_2_fu_2583_p2 = (xor_ln942_23_fu_2577_p2 & p_Result_70_reg_3996);

assign underflow_3_fu_2695_p2 = (xor_ln942_24_fu_2689_p2 & p_Result_73_reg_4040);

assign underflow_4_fu_2807_p2 = (xor_ln942_25_fu_2801_p2 & p_Result_76_reg_4084);

assign underflow_5_fu_2919_p2 = (xor_ln942_26_fu_2913_p2 & p_Result_79_reg_4128);

assign underflow_6_fu_3031_p2 = (xor_ln942_27_fu_3025_p2 & p_Result_82_reg_4172);

assign underflow_7_fu_3143_p2 = (xor_ln942_28_fu_3137_p2 & p_Result_85_reg_4216);

assign underflow_8_fu_3255_p2 = (xor_ln942_29_fu_3249_p2 & p_Result_88_reg_4260);

assign underflow_9_fu_3367_p2 = (xor_ln942_30_fu_3361_p2 & p_Result_91_reg_4304);

assign underflow_fu_679_p2 = (or_ln942_fu_668_p2 & and_ln942_fu_674_p2);

assign xor_ln936_1_fu_2520_p2 = (tmp_77_fu_2513_p3 ^ 1'd1);

assign xor_ln936_2_fu_2632_p2 = (tmp_82_fu_2625_p3 ^ 1'd1);

assign xor_ln936_3_fu_2744_p2 = (tmp_87_fu_2737_p3 ^ 1'd1);

assign xor_ln936_4_fu_2856_p2 = (tmp_92_fu_2849_p3 ^ 1'd1);

assign xor_ln936_5_fu_2968_p2 = (tmp_97_fu_2961_p3 ^ 1'd1);

assign xor_ln936_6_fu_3080_p2 = (tmp_102_fu_3073_p3 ^ 1'd1);

assign xor_ln936_7_fu_3192_p2 = (tmp_107_fu_3185_p3 ^ 1'd1);

assign xor_ln936_8_fu_3304_p2 = (tmp_112_fu_3297_p3 ^ 1'd1);

assign xor_ln936_9_fu_3416_p2 = (tmp_117_fu_3409_p3 ^ 1'd1);

assign xor_ln936_fu_2408_p2 = (tmp_72_fu_2401_p3 ^ 1'd1);

assign xor_ln937_fu_633_p2 = (p_Result_65_reg_3818 ^ 1'd1);

assign xor_ln941_10_fu_2890_p2 = (p_Result_79_reg_4128 ^ 1'd1);

assign xor_ln941_11_fu_2991_p2 = (deleted_zeros_6_fu_2955_p3 ^ 1'd1);

assign xor_ln941_12_fu_3002_p2 = (p_Result_82_reg_4172 ^ 1'd1);

assign xor_ln941_13_fu_3103_p2 = (deleted_zeros_7_fu_3067_p3 ^ 1'd1);

assign xor_ln941_14_fu_3114_p2 = (p_Result_85_reg_4216 ^ 1'd1);

assign xor_ln941_15_fu_3215_p2 = (deleted_zeros_8_fu_3179_p3 ^ 1'd1);

assign xor_ln941_16_fu_3226_p2 = (p_Result_88_reg_4260 ^ 1'd1);

assign xor_ln941_17_fu_3327_p2 = (deleted_zeros_9_fu_3291_p3 ^ 1'd1);

assign xor_ln941_18_fu_3338_p2 = (p_Result_91_reg_4304 ^ 1'd1);

assign xor_ln941_19_fu_3439_p2 = (deleted_zeros_10_fu_3403_p3 ^ 1'd1);

assign xor_ln941_1_fu_2431_p2 = (deleted_zeros_1_fu_2395_p3 ^ 1'd1);

assign xor_ln941_20_fu_3450_p2 = (p_Result_94_reg_4348 ^ 1'd1);

assign xor_ln941_2_fu_2442_p2 = (p_Result_67_reg_3952 ^ 1'd1);

assign xor_ln941_3_fu_2543_p2 = (deleted_zeros_2_fu_2507_p3 ^ 1'd1);

assign xor_ln941_4_fu_2554_p2 = (p_Result_70_reg_3996 ^ 1'd1);

assign xor_ln941_5_fu_2655_p2 = (deleted_zeros_3_fu_2619_p3 ^ 1'd1);

assign xor_ln941_6_fu_2666_p2 = (p_Result_73_reg_4040 ^ 1'd1);

assign xor_ln941_7_fu_2767_p2 = (deleted_zeros_4_fu_2731_p3 ^ 1'd1);

assign xor_ln941_8_fu_2778_p2 = (p_Result_76_reg_4084 ^ 1'd1);

assign xor_ln941_9_fu_2879_p2 = (deleted_zeros_5_fu_2843_p3 ^ 1'd1);

assign xor_ln941_fu_644_p2 = (deleted_zeros_fu_619_p3 ^ 1'd1);

assign xor_ln942_10_fu_2833_p2 = (p_Result_81_reg_4144 ^ 1'd1);

assign xor_ln942_11_fu_2901_p2 = (deleted_ones_5_fu_2867_p3 ^ 1'd1);

assign xor_ln942_12_fu_2945_p2 = (p_Result_84_reg_4188 ^ 1'd1);

assign xor_ln942_13_fu_3013_p2 = (deleted_ones_6_fu_2979_p3 ^ 1'd1);

assign xor_ln942_14_fu_3057_p2 = (p_Result_87_reg_4232 ^ 1'd1);

assign xor_ln942_15_fu_3125_p2 = (deleted_ones_7_fu_3091_p3 ^ 1'd1);

assign xor_ln942_16_fu_3169_p2 = (p_Result_90_reg_4276 ^ 1'd1);

assign xor_ln942_17_fu_3237_p2 = (deleted_ones_8_fu_3203_p3 ^ 1'd1);

assign xor_ln942_18_fu_3281_p2 = (p_Result_93_reg_4320 ^ 1'd1);

assign xor_ln942_19_fu_3349_p2 = (deleted_ones_9_fu_3315_p3 ^ 1'd1);

assign xor_ln942_1_fu_662_p2 = (deleted_ones_fu_626_p3 ^ 1'd1);

assign xor_ln942_20_fu_3393_p2 = (p_Result_96_reg_4364 ^ 1'd1);

assign xor_ln942_21_fu_3461_p2 = (deleted_ones_10_fu_3427_p3 ^ 1'd1);

assign xor_ln942_22_fu_2465_p2 = (or_ln942_1_fu_2459_p2 ^ and_ln937_fu_2426_p2);

assign xor_ln942_23_fu_2577_p2 = (or_ln942_2_fu_2571_p2 ^ and_ln937_1_fu_2538_p2);

assign xor_ln942_24_fu_2689_p2 = (or_ln942_3_fu_2683_p2 ^ and_ln937_2_fu_2650_p2);

assign xor_ln942_25_fu_2801_p2 = (or_ln942_4_fu_2795_p2 ^ and_ln937_3_fu_2762_p2);

assign xor_ln942_26_fu_2913_p2 = (or_ln942_5_fu_2907_p2 ^ and_ln937_4_fu_2874_p2);

assign xor_ln942_27_fu_3025_p2 = (or_ln942_6_fu_3019_p2 ^ and_ln937_5_fu_2986_p2);

assign xor_ln942_28_fu_3137_p2 = (or_ln942_7_fu_3131_p2 ^ and_ln937_6_fu_3098_p2);

assign xor_ln942_29_fu_3249_p2 = (or_ln942_8_fu_3243_p2 ^ and_ln937_7_fu_3210_p2);

assign xor_ln942_2_fu_2385_p2 = (p_Result_69_reg_3968 ^ 1'd1);

assign xor_ln942_30_fu_3361_p2 = (or_ln942_9_fu_3355_p2 ^ and_ln937_8_fu_3322_p2);

assign xor_ln942_31_fu_3473_p2 = (or_ln942_10_fu_3467_p2 ^ and_ln937_9_fu_3434_p2);

assign xor_ln942_3_fu_2453_p2 = (deleted_ones_1_fu_2419_p3 ^ 1'd1);

assign xor_ln942_4_fu_2497_p2 = (p_Result_72_reg_4012 ^ 1'd1);

assign xor_ln942_5_fu_2565_p2 = (deleted_ones_2_fu_2531_p3 ^ 1'd1);

assign xor_ln942_6_fu_2609_p2 = (p_Result_75_reg_4056 ^ 1'd1);

assign xor_ln942_7_fu_2677_p2 = (deleted_ones_3_fu_2643_p3 ^ 1'd1);

assign xor_ln942_8_fu_2721_p2 = (p_Result_78_reg_4100 ^ 1'd1);

assign xor_ln942_9_fu_2789_p2 = (deleted_ones_4_fu_2755_p3 ^ 1'd1);

assign xor_ln942_fu_603_p2 = (p_Result_66_fu_595_p3 ^ 1'd1);

assign zext_ln271_fu_543_p1 = ap_sig_allocacmp_cii_1;

assign zext_ln423_10_fu_977_p1 = trunc_ln864_17_fu_959_p1;

assign zext_ln423_11_fu_1141_p1 = tmp_70_fu_1134_p3;

assign zext_ln423_12_fu_1273_p1 = tmp_75_fu_1266_p3;

assign zext_ln423_13_fu_1405_p1 = tmp_80_fu_1398_p3;

assign zext_ln423_14_fu_1537_p1 = tmp_85_fu_1530_p3;

assign zext_ln423_15_fu_1669_p1 = tmp_90_fu_1662_p3;

assign zext_ln423_16_fu_1801_p1 = tmp_95_fu_1794_p3;

assign zext_ln423_17_fu_1933_p1 = tmp_100_fu_1926_p3;

assign zext_ln423_18_fu_2065_p1 = tmp_105_fu_2058_p3;

assign zext_ln423_19_fu_2197_p1 = tmp_110_fu_2190_p3;

assign zext_ln423_1_fu_725_p1 = trunc_ln864_fu_707_p1;

assign zext_ln423_20_fu_2329_p1 = tmp_115_fu_2322_p3;

assign zext_ln423_2_fu_753_p1 = trunc_ln864_1_fu_735_p1;

assign zext_ln423_3_fu_781_p1 = trunc_ln864_3_fu_763_p1;

assign zext_ln423_4_fu_809_p1 = trunc_ln864_5_fu_791_p1;

assign zext_ln423_5_fu_837_p1 = trunc_ln864_7_fu_819_p1;

assign zext_ln423_6_fu_865_p1 = trunc_ln864_9_fu_847_p1;

assign zext_ln423_7_fu_893_p1 = trunc_ln864_11_fu_875_p1;

assign zext_ln423_8_fu_921_p1 = trunc_ln864_13_fu_903_p1;

assign zext_ln423_9_fu_949_p1 = trunc_ln864_15_fu_931_p1;

assign zext_ln423_fu_587_p1 = tmp_66_reg_3824;

always @ (posedge ap_clk) begin
    zext_ln271_reg_3786[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //FracNet_T_matmul_Pipeline_VITIS_LOOP_271_2
