// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FracNet_T_compute_engine_64 (
        ap_clk,
        ap_rst,
        b,
        w,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [63:0] b;
input  [63:0] w;
output  [6:0] ap_return;

wire   [1:0] trunc_ln1543_fu_602_p1;
reg   [1:0] trunc_ln1543_reg_1882;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln1543_1_fu_890_p4;
reg   [1:0] trunc_ln1543_1_reg_1887;
reg   [3:0] trunc_ln3_reg_1892;
reg   [3:0] tmp_48_reg_1897;
reg   [3:0] tmp_49_reg_1902;
reg   [3:0] tmp_50_reg_1907;
reg   [3:0] tmp_51_reg_1912;
reg   [3:0] tmp_52_reg_1917;
reg   [3:0] tmp_53_reg_1922;
wire   [3:0] trunc_ln16_fu_1552_p1;
reg   [3:0] trunc_ln16_reg_1927;
reg   [3:0] tmp_54_reg_1932;
reg   [3:0] tmp_55_reg_1937;
reg   [3:0] tmp_56_reg_1942;
reg   [3:0] tmp_57_reg_1948;
reg   [3:0] tmp_58_reg_1954;
reg   [3:0] tmp_59_reg_1960;
reg   [3:0] tmp_60_reg_1966;
reg   [3:0] tmp_61_reg_1973;
reg   [3:0] tmp_62_reg_1978;
reg   [3:0] tmp_63_reg_1983;
reg   [3:0] tmp_64_reg_1988;
wire   [3:0] trunc_ln886_fu_1666_p1;
reg   [3:0] trunc_ln886_reg_1993;
wire    ap_block_pp0_stage0;
wire   [63:0] ret_V_13_fu_200_p2;
wire   [0:0] tmp_fu_206_p3;
wire   [0:0] tmp_118_fu_214_p3;
wire   [0:0] tmp_119_fu_222_p3;
wire   [0:0] tmp_120_fu_230_p3;
wire   [0:0] tmp_121_fu_238_p3;
wire   [0:0] tmp_122_fu_246_p3;
wire   [0:0] tmp_123_fu_254_p3;
wire   [0:0] tmp_124_fu_262_p3;
wire   [0:0] tmp_125_fu_270_p3;
wire   [0:0] tmp_126_fu_278_p3;
wire   [0:0] tmp_127_fu_286_p3;
wire   [0:0] tmp_128_fu_294_p3;
wire   [0:0] tmp_129_fu_302_p3;
wire   [0:0] tmp_130_fu_310_p3;
wire   [0:0] tmp_131_fu_318_p3;
wire   [0:0] tmp_132_fu_326_p3;
wire   [0:0] tmp_133_fu_334_p3;
wire   [0:0] tmp_134_fu_342_p3;
wire   [0:0] tmp_135_fu_350_p3;
wire   [0:0] tmp_136_fu_358_p3;
wire   [0:0] tmp_137_fu_366_p3;
wire   [0:0] tmp_138_fu_374_p3;
wire   [0:0] tmp_139_fu_382_p3;
wire   [0:0] tmp_140_fu_390_p3;
wire   [0:0] tmp_141_fu_398_p3;
wire   [0:0] tmp_142_fu_406_p3;
wire   [0:0] tmp_143_fu_414_p3;
wire   [0:0] tmp_144_fu_422_p3;
wire   [0:0] tmp_145_fu_430_p3;
wire   [0:0] tmp_146_fu_438_p3;
wire   [0:0] tmp_147_fu_446_p3;
wire   [0:0] tmp_148_fu_454_p3;
wire   [62:0] ret_V_fu_462_p64;
wire   [63:0] zext_ln1543_fu_592_p1;
wire   [63:0] x_V_5_fu_596_p2;
wire   [1:0] tmp_s_fu_606_p4;
wire   [1:0] tmp_19_fu_616_p4;
wire   [1:0] tmp_20_fu_626_p4;
wire   [1:0] tmp_21_fu_636_p4;
wire   [1:0] tmp_22_fu_646_p4;
wire   [1:0] tmp_23_fu_656_p4;
wire   [1:0] tmp_24_fu_666_p4;
wire   [1:0] tmp_25_fu_676_p4;
wire   [1:0] tmp_26_fu_686_p4;
wire   [1:0] tmp_27_fu_696_p4;
wire   [1:0] tmp_28_fu_706_p4;
wire   [1:0] tmp_29_fu_716_p4;
wire   [1:0] tmp_30_fu_726_p4;
wire   [1:0] tmp_31_fu_736_p4;
wire   [1:0] tmp_32_fu_746_p4;
wire   [61:0] ret_V_11_fu_756_p32;
wire   [1:0] tmp_33_fu_900_p4;
wire   [1:0] tmp_34_fu_910_p4;
wire   [1:0] tmp_35_fu_920_p4;
wire   [1:0] tmp_36_fu_930_p4;
wire   [1:0] tmp_37_fu_940_p4;
wire   [1:0] tmp_38_fu_950_p4;
wire   [1:0] tmp_39_fu_960_p4;
wire   [1:0] tmp_40_fu_970_p4;
wire   [1:0] tmp_41_fu_980_p4;
wire   [1:0] tmp_42_fu_990_p4;
wire   [1:0] tmp_43_fu_1000_p4;
wire   [1:0] tmp_44_fu_1010_p4;
wire   [1:0] tmp_45_fu_1020_p4;
wire   [1:0] tmp_46_fu_1030_p4;
wire   [1:0] tmp_47_fu_1040_p4;
wire   [61:0] ret_V_12_fu_1050_p32;
wire   [58:0] ret_V_11_cast_fu_822_p31;
wire   [58:0] ret_V_12_cast_fu_1116_p31;
wire   [62:0] zext_ln1543_2_fu_1180_p1;
wire   [62:0] zext_ln1543_1_fu_886_p1;
wire   [50:0] trunc_ln16_1_fu_1204_p27;
wire   [50:0] trunc_ln16_2_fu_1264_p27;
wire   [59:0] zext_ln232_3_fu_1188_p1;
wire   [59:0] zext_ln232_2_fu_1184_p1;
wire   [62:0] x_V_fu_1198_p2;
wire   [58:0] trunc_ln1715_2_fu_1330_p4;
wire   [58:0] add_ln232_1_fu_1192_p2;
wire   [34:0] trunc_ln232_3_fu_1354_p19;
wire   [34:0] trunc_ln232_4_fu_1398_p19;
wire   [51:0] zext_ln16_1_fu_1320_p1;
wire   [51:0] zext_ln16_fu_1260_p1;
wire   [59:0] zext_ln1715_fu_1340_p1;
wire   [59:0] add_ln16_fu_1324_p2;
wire   [35:0] zext_ln232_5_fu_1438_p1;
wire   [35:0] zext_ln232_4_fu_1394_p1;
wire   [51:0] trunc_ln232_5_cast_fu_1448_p4;
wire   [51:0] add_ln232_2_fu_1442_p2;
wire   [35:0] trunc_ln232_6_cast_fu_1470_p4;
wire   [35:0] add_ln232_5_fu_1464_p2;
wire   [51:0] add_ln232_6_fu_1480_p2;
wire   [59:0] add_ln232_fu_1458_p2;
wire   [35:0] add_ln16_1_fu_1486_p2;
wire   [3:0] zext_ln232_fu_1670_p1;
wire   [3:0] add_ln232_4_fu_1676_p2;
wire   [3:0] zext_ln232_1_fu_1673_p1;
wire   [52:0] and_ln_fu_1687_p15;
wire   [51:0] trunc_ln1715_3_fu_1716_p14;
wire   [3:0] add_ln232_3_fu_1681_p2;
wire   [4:0] trunc_ln4_fu_1747_p3;
wire   [36:0] and_ln1_fu_1758_p11;
wire   [36:0] trunc_ln886_3_fu_1781_p11;
wire   [53:0] zext_ln886_fu_1739_p1;
wire   [53:0] zext_ln1715_1_fu_1712_p1;
wire   [37:0] zext_ln886_4_fu_1800_p1;
wire   [37:0] zext_ln886_3_fu_1777_p1;
wire   [37:0] add_ln16_2_fu_1810_p2;
wire   [53:0] x_V_3_fu_1804_p2;
wire   [37:0] tmp_149_fu_1820_p4;
wire   [38:0] zext_ln1715_2_fu_1830_p1;
wire   [38:0] zext_ln16_2_fu_1816_p1;
wire   [38:0] x_V_4_fu_1844_p2;
wire   [5:0] zext_ln886_2_fu_1754_p1;
wire   [5:0] zext_ln886_1_fu_1743_p1;
wire   [5:0] add_ln1543_fu_1860_p2;
wire   [6:0] trunc_ln886_1_fu_1834_p4;
wire   [6:0] trunc_ln886_2_fu_1850_p4;
wire   [6:0] add_ln1543_1_fu_1870_p2;
wire   [6:0] zext_ln1543_3_fu_1866_p1;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_48_reg_1897 <= {{add_ln232_6_fu_1480_p2[51:48]}};
        tmp_49_reg_1902 <= {{add_ln232_6_fu_1480_p2[43:40]}};
        tmp_50_reg_1907 <= {{add_ln232_6_fu_1480_p2[35:32]}};
        tmp_51_reg_1912 <= {{add_ln232_6_fu_1480_p2[27:24]}};
        tmp_52_reg_1917 <= {{add_ln232_6_fu_1480_p2[19:16]}};
        tmp_53_reg_1922 <= {{add_ln232_6_fu_1480_p2[11:8]}};
        tmp_54_reg_1932 <= {{add_ln232_fu_1458_p2[59:56]}};
        tmp_55_reg_1937 <= {{add_ln232_fu_1458_p2[51:48]}};
        tmp_56_reg_1942 <= {{add_ln232_fu_1458_p2[43:40]}};
        tmp_57_reg_1948 <= {{add_ln232_fu_1458_p2[35:32]}};
        tmp_58_reg_1954 <= {{add_ln232_fu_1458_p2[27:24]}};
        tmp_59_reg_1960 <= {{add_ln232_fu_1458_p2[19:16]}};
        tmp_60_reg_1966 <= {{add_ln232_fu_1458_p2[11:8]}};
        tmp_61_reg_1973 <= {{add_ln16_1_fu_1486_p2[35:32]}};
        tmp_62_reg_1978 <= {{add_ln16_1_fu_1486_p2[27:24]}};
        tmp_63_reg_1983 <= {{add_ln16_1_fu_1486_p2[19:16]}};
        tmp_64_reg_1988 <= {{add_ln16_1_fu_1486_p2[11:8]}};
        trunc_ln1543_1_reg_1887 <= {{x_V_5_fu_596_p2[3:2]}};
        trunc_ln1543_reg_1882 <= trunc_ln1543_fu_602_p1;
        trunc_ln16_reg_1927 <= trunc_ln16_fu_1552_p1;
        trunc_ln3_reg_1892 <= {{add_ln232_1_fu_1192_p2[7:4]}};
        trunc_ln886_reg_1993 <= trunc_ln886_fu_1666_p1;
    end
end

assign add_ln1543_1_fu_1870_p2 = (trunc_ln886_1_fu_1834_p4 + trunc_ln886_2_fu_1850_p4);

assign add_ln1543_fu_1860_p2 = (zext_ln886_2_fu_1754_p1 + zext_ln886_1_fu_1743_p1);

assign add_ln16_1_fu_1486_p2 = (trunc_ln232_6_cast_fu_1470_p4 + add_ln232_5_fu_1464_p2);

assign add_ln16_2_fu_1810_p2 = (zext_ln886_4_fu_1800_p1 + zext_ln886_3_fu_1777_p1);

assign add_ln16_fu_1324_p2 = (zext_ln232_3_fu_1188_p1 + zext_ln232_2_fu_1184_p1);

assign add_ln232_1_fu_1192_p2 = (ret_V_12_cast_fu_1116_p31 + ret_V_11_cast_fu_822_p31);

assign add_ln232_2_fu_1442_p2 = (zext_ln16_1_fu_1320_p1 + zext_ln16_fu_1260_p1);

assign add_ln232_3_fu_1681_p2 = (add_ln232_4_fu_1676_p2 + zext_ln232_1_fu_1673_p1);

assign add_ln232_4_fu_1676_p2 = (zext_ln232_fu_1670_p1 + trunc_ln3_reg_1892);

assign add_ln232_5_fu_1464_p2 = (zext_ln232_5_fu_1438_p1 + zext_ln232_4_fu_1394_p1);

assign add_ln232_6_fu_1480_p2 = (trunc_ln232_5_cast_fu_1448_p4 + add_ln232_2_fu_1442_p2);

assign add_ln232_fu_1458_p2 = (zext_ln1715_fu_1340_p1 + add_ln16_fu_1324_p2);

assign and_ln1_fu_1758_p11 = {{{{{{{{{{{{{{{{{{1'd0}, {tmp_61_reg_1973}}}, {4'd0}}}, {tmp_62_reg_1978}}}, {4'd0}}}, {tmp_63_reg_1983}}}, {4'd0}}}, {tmp_64_reg_1988}}}, {4'd0}}}, {trunc_ln886_reg_1993}};

assign and_ln_fu_1687_p15 = {{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_48_reg_1897}}}, {4'd0}}}, {tmp_49_reg_1902}}}, {4'd0}}}, {tmp_50_reg_1907}}}, {4'd0}}}, {tmp_51_reg_1912}}}, {4'd0}}}, {tmp_52_reg_1917}}}, {4'd0}}}, {tmp_53_reg_1922}}}, {4'd0}}}, {trunc_ln16_reg_1927}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return = (add_ln1543_1_fu_1870_p2 + zext_ln1543_3_fu_1866_p1);

assign ret_V_11_cast_fu_822_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_19_fu_616_p4}}}, {2'd0}}}, {tmp_20_fu_626_p4}}}, {2'd0}}}, {tmp_21_fu_636_p4}}}, {2'd0}}}, {tmp_22_fu_646_p4}}}, {2'd0}}}, {tmp_23_fu_656_p4}}}, {2'd0}}}, {tmp_24_fu_666_p4}}}, {2'd0}}}, {tmp_25_fu_676_p4}}}, {2'd0}}}, {tmp_26_fu_686_p4}}}, {2'd0}}}, {tmp_27_fu_696_p4}}}, {2'd0}}}, {tmp_28_fu_706_p4}}}, {2'd0}}}, {tmp_29_fu_716_p4}}}, {2'd0}}}, {tmp_30_fu_726_p4}}}, {2'd0}}}, {tmp_31_fu_736_p4}}}, {2'd0}}}, {tmp_32_fu_746_p4}}}, {2'd0}}}, {trunc_ln1543_fu_602_p1}};

assign ret_V_11_fu_756_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_s_fu_606_p4}, {2'd0}}, {tmp_19_fu_616_p4}}, {2'd0}}, {tmp_20_fu_626_p4}}, {2'd0}}, {tmp_21_fu_636_p4}}, {2'd0}}, {tmp_22_fu_646_p4}}, {2'd0}}, {tmp_23_fu_656_p4}}, {2'd0}}, {tmp_24_fu_666_p4}}, {2'd0}}, {tmp_25_fu_676_p4}}, {2'd0}}, {tmp_26_fu_686_p4}}, {2'd0}}, {tmp_27_fu_696_p4}}, {2'd0}}, {tmp_28_fu_706_p4}}, {2'd0}}, {tmp_29_fu_716_p4}}, {2'd0}}, {tmp_30_fu_726_p4}}, {2'd0}}, {tmp_31_fu_736_p4}}, {2'd0}}, {tmp_32_fu_746_p4}}, {2'd0}}, {trunc_ln1543_fu_602_p1}};

assign ret_V_12_cast_fu_1116_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_34_fu_910_p4}}}, {2'd0}}}, {tmp_35_fu_920_p4}}}, {2'd0}}}, {tmp_36_fu_930_p4}}}, {2'd0}}}, {tmp_37_fu_940_p4}}}, {2'd0}}}, {tmp_38_fu_950_p4}}}, {2'd0}}}, {tmp_39_fu_960_p4}}}, {2'd0}}}, {tmp_40_fu_970_p4}}}, {2'd0}}}, {tmp_41_fu_980_p4}}}, {2'd0}}}, {tmp_42_fu_990_p4}}}, {2'd0}}}, {tmp_43_fu_1000_p4}}}, {2'd0}}}, {tmp_44_fu_1010_p4}}}, {2'd0}}}, {tmp_45_fu_1020_p4}}}, {2'd0}}}, {tmp_46_fu_1030_p4}}}, {2'd0}}}, {tmp_47_fu_1040_p4}}}, {2'd0}}}, {trunc_ln1543_1_fu_890_p4}};

assign ret_V_12_fu_1050_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_33_fu_900_p4}, {2'd0}}, {tmp_34_fu_910_p4}}, {2'd0}}, {tmp_35_fu_920_p4}}, {2'd0}}, {tmp_36_fu_930_p4}}, {2'd0}}, {tmp_37_fu_940_p4}}, {2'd0}}, {tmp_38_fu_950_p4}}, {2'd0}}, {tmp_39_fu_960_p4}}, {2'd0}}, {tmp_40_fu_970_p4}}, {2'd0}}, {tmp_41_fu_980_p4}}, {2'd0}}, {tmp_42_fu_990_p4}}, {2'd0}}, {tmp_43_fu_1000_p4}}, {2'd0}}, {tmp_44_fu_1010_p4}}, {2'd0}}, {tmp_45_fu_1020_p4}}, {2'd0}}, {tmp_46_fu_1030_p4}}, {2'd0}}, {tmp_47_fu_1040_p4}}, {2'd0}}, {trunc_ln1543_1_fu_890_p4}};

assign ret_V_13_fu_200_p2 = (w ^ b);

assign ret_V_fu_462_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_fu_206_p3}, {1'd0}}, {tmp_118_fu_214_p3}}, {1'd0}}, {tmp_119_fu_222_p3}}, {1'd0}}, {tmp_120_fu_230_p3}}, {1'd0}}, {tmp_121_fu_238_p3}}, {1'd0}}, {tmp_122_fu_246_p3}}, {1'd0}}, {tmp_123_fu_254_p3}}, {1'd0}}, {tmp_124_fu_262_p3}}, {1'd0}}, {tmp_125_fu_270_p3}}, {1'd0}}, {tmp_126_fu_278_p3}}, {1'd0}}, {tmp_127_fu_286_p3}}, {1'd0}}, {tmp_128_fu_294_p3}}, {1'd0}}, {tmp_129_fu_302_p3}}, {1'd0}}, {tmp_130_fu_310_p3}}, {1'd0}}, {tmp_131_fu_318_p3}}, {1'd0}}, {tmp_132_fu_326_p3}}, {1'd0}}, {tmp_133_fu_334_p3}}, {1'd0}}, {tmp_134_fu_342_p3}}, {1'd0}}, {tmp_135_fu_350_p3}}, {1'd0}}, {tmp_136_fu_358_p3}}, {1'd0}}, {tmp_137_fu_366_p3}}, {1'd0}}, {tmp_138_fu_374_p3}}, {1'd0}}, {tmp_139_fu_382_p3}}, {1'd0}}, {tmp_140_fu_390_p3}}, {1'd0}}, {tmp_141_fu_398_p3}}, {1'd0}}, {tmp_142_fu_406_p3}}, {1'd0}}, {tmp_143_fu_414_p3}}, {1'd0}}, {tmp_144_fu_422_p3}}, {1'd0}}, {tmp_145_fu_430_p3}}, {1'd0}}, {tmp_146_fu_438_p3}}, {1'd0}}, {tmp_147_fu_446_p3}}, {1'd0}}, {tmp_148_fu_454_p3}};

assign tmp_118_fu_214_p3 = ret_V_13_fu_200_p2[32'd61];

assign tmp_119_fu_222_p3 = ret_V_13_fu_200_p2[32'd59];

assign tmp_120_fu_230_p3 = ret_V_13_fu_200_p2[32'd57];

assign tmp_121_fu_238_p3 = ret_V_13_fu_200_p2[32'd55];

assign tmp_122_fu_246_p3 = ret_V_13_fu_200_p2[32'd53];

assign tmp_123_fu_254_p3 = ret_V_13_fu_200_p2[32'd51];

assign tmp_124_fu_262_p3 = ret_V_13_fu_200_p2[32'd49];

assign tmp_125_fu_270_p3 = ret_V_13_fu_200_p2[32'd47];

assign tmp_126_fu_278_p3 = ret_V_13_fu_200_p2[32'd45];

assign tmp_127_fu_286_p3 = ret_V_13_fu_200_p2[32'd43];

assign tmp_128_fu_294_p3 = ret_V_13_fu_200_p2[32'd41];

assign tmp_129_fu_302_p3 = ret_V_13_fu_200_p2[32'd39];

assign tmp_130_fu_310_p3 = ret_V_13_fu_200_p2[32'd37];

assign tmp_131_fu_318_p3 = ret_V_13_fu_200_p2[32'd35];

assign tmp_132_fu_326_p3 = ret_V_13_fu_200_p2[32'd33];

assign tmp_133_fu_334_p3 = ret_V_13_fu_200_p2[32'd31];

assign tmp_134_fu_342_p3 = ret_V_13_fu_200_p2[32'd29];

assign tmp_135_fu_350_p3 = ret_V_13_fu_200_p2[32'd27];

assign tmp_136_fu_358_p3 = ret_V_13_fu_200_p2[32'd25];

assign tmp_137_fu_366_p3 = ret_V_13_fu_200_p2[32'd23];

assign tmp_138_fu_374_p3 = ret_V_13_fu_200_p2[32'd21];

assign tmp_139_fu_382_p3 = ret_V_13_fu_200_p2[32'd19];

assign tmp_140_fu_390_p3 = ret_V_13_fu_200_p2[32'd17];

assign tmp_141_fu_398_p3 = ret_V_13_fu_200_p2[32'd15];

assign tmp_142_fu_406_p3 = ret_V_13_fu_200_p2[32'd13];

assign tmp_143_fu_414_p3 = ret_V_13_fu_200_p2[32'd11];

assign tmp_144_fu_422_p3 = ret_V_13_fu_200_p2[32'd9];

assign tmp_145_fu_430_p3 = ret_V_13_fu_200_p2[32'd7];

assign tmp_146_fu_438_p3 = ret_V_13_fu_200_p2[32'd5];

assign tmp_147_fu_446_p3 = ret_V_13_fu_200_p2[32'd3];

assign tmp_148_fu_454_p3 = ret_V_13_fu_200_p2[32'd1];

assign tmp_149_fu_1820_p4 = {{x_V_3_fu_1804_p2[53:16]}};

assign tmp_19_fu_616_p4 = {{x_V_5_fu_596_p2[57:56]}};

assign tmp_20_fu_626_p4 = {{x_V_5_fu_596_p2[53:52]}};

assign tmp_21_fu_636_p4 = {{x_V_5_fu_596_p2[49:48]}};

assign tmp_22_fu_646_p4 = {{x_V_5_fu_596_p2[45:44]}};

assign tmp_23_fu_656_p4 = {{x_V_5_fu_596_p2[41:40]}};

assign tmp_24_fu_666_p4 = {{x_V_5_fu_596_p2[37:36]}};

assign tmp_25_fu_676_p4 = {{x_V_5_fu_596_p2[33:32]}};

assign tmp_26_fu_686_p4 = {{x_V_5_fu_596_p2[29:28]}};

assign tmp_27_fu_696_p4 = {{x_V_5_fu_596_p2[25:24]}};

assign tmp_28_fu_706_p4 = {{x_V_5_fu_596_p2[21:20]}};

assign tmp_29_fu_716_p4 = {{x_V_5_fu_596_p2[17:16]}};

assign tmp_30_fu_726_p4 = {{x_V_5_fu_596_p2[13:12]}};

assign tmp_31_fu_736_p4 = {{x_V_5_fu_596_p2[9:8]}};

assign tmp_32_fu_746_p4 = {{x_V_5_fu_596_p2[5:4]}};

assign tmp_33_fu_900_p4 = {{x_V_5_fu_596_p2[63:62]}};

assign tmp_34_fu_910_p4 = {{x_V_5_fu_596_p2[59:58]}};

assign tmp_35_fu_920_p4 = {{x_V_5_fu_596_p2[55:54]}};

assign tmp_36_fu_930_p4 = {{x_V_5_fu_596_p2[51:50]}};

assign tmp_37_fu_940_p4 = {{x_V_5_fu_596_p2[47:46]}};

assign tmp_38_fu_950_p4 = {{x_V_5_fu_596_p2[43:42]}};

assign tmp_39_fu_960_p4 = {{x_V_5_fu_596_p2[39:38]}};

assign tmp_40_fu_970_p4 = {{x_V_5_fu_596_p2[35:34]}};

assign tmp_41_fu_980_p4 = {{x_V_5_fu_596_p2[31:30]}};

assign tmp_42_fu_990_p4 = {{x_V_5_fu_596_p2[27:26]}};

assign tmp_43_fu_1000_p4 = {{x_V_5_fu_596_p2[23:22]}};

assign tmp_44_fu_1010_p4 = {{x_V_5_fu_596_p2[19:18]}};

assign tmp_45_fu_1020_p4 = {{x_V_5_fu_596_p2[15:14]}};

assign tmp_46_fu_1030_p4 = {{x_V_5_fu_596_p2[11:10]}};

assign tmp_47_fu_1040_p4 = {{x_V_5_fu_596_p2[7:6]}};

assign tmp_fu_206_p3 = ret_V_13_fu_200_p2[32'd63];

assign tmp_s_fu_606_p4 = {{x_V_5_fu_596_p2[61:60]}};

assign trunc_ln1543_1_fu_890_p4 = {{x_V_5_fu_596_p2[3:2]}};

assign trunc_ln1543_fu_602_p1 = x_V_5_fu_596_p2[1:0];

assign trunc_ln16_1_fu_1204_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_21_fu_636_p4}}}, {2'd0}}}, {tmp_22_fu_646_p4}}}, {2'd0}}}, {tmp_23_fu_656_p4}}}, {2'd0}}}, {tmp_24_fu_666_p4}}}, {2'd0}}}, {tmp_25_fu_676_p4}}}, {2'd0}}}, {tmp_26_fu_686_p4}}}, {2'd0}}}, {tmp_27_fu_696_p4}}}, {2'd0}}}, {tmp_28_fu_706_p4}}}, {2'd0}}}, {tmp_29_fu_716_p4}}}, {2'd0}}}, {tmp_30_fu_726_p4}}}, {2'd0}}}, {tmp_31_fu_736_p4}}}, {2'd0}}}, {tmp_32_fu_746_p4}}}, {2'd0}}}, {trunc_ln1543_fu_602_p1}};

assign trunc_ln16_2_fu_1264_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_36_fu_930_p4}}}, {2'd0}}}, {tmp_37_fu_940_p4}}}, {2'd0}}}, {tmp_38_fu_950_p4}}}, {2'd0}}}, {tmp_39_fu_960_p4}}}, {2'd0}}}, {tmp_40_fu_970_p4}}}, {2'd0}}}, {tmp_41_fu_980_p4}}}, {2'd0}}}, {tmp_42_fu_990_p4}}}, {2'd0}}}, {tmp_43_fu_1000_p4}}}, {2'd0}}}, {tmp_44_fu_1010_p4}}}, {2'd0}}}, {tmp_45_fu_1020_p4}}}, {2'd0}}}, {tmp_46_fu_1030_p4}}}, {2'd0}}}, {tmp_47_fu_1040_p4}}}, {2'd0}}}, {trunc_ln1543_1_fu_890_p4}};

assign trunc_ln16_fu_1552_p1 = add_ln232_6_fu_1480_p2[3:0];

assign trunc_ln1715_2_fu_1330_p4 = {{x_V_fu_1198_p2[62:4]}};

assign trunc_ln1715_3_fu_1716_p14 = {{{{{{{{{{{{{tmp_54_reg_1932}, {4'd0}}, {tmp_55_reg_1937}}, {4'd0}}, {tmp_56_reg_1942}}, {4'd0}}, {tmp_57_reg_1948}}, {4'd0}}, {tmp_58_reg_1954}}, {4'd0}}, {tmp_59_reg_1960}}, {4'd0}}, {tmp_60_reg_1966}};

assign trunc_ln232_3_fu_1354_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_25_fu_676_p4}}}, {2'd0}}}, {tmp_26_fu_686_p4}}}, {2'd0}}}, {tmp_27_fu_696_p4}}}, {2'd0}}}, {tmp_28_fu_706_p4}}}, {2'd0}}}, {tmp_29_fu_716_p4}}}, {2'd0}}}, {tmp_30_fu_726_p4}}}, {2'd0}}}, {tmp_31_fu_736_p4}}}, {2'd0}}}, {tmp_32_fu_746_p4}}}, {2'd0}}}, {trunc_ln1543_fu_602_p1}};

assign trunc_ln232_4_fu_1398_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_40_fu_970_p4}}}, {2'd0}}}, {tmp_41_fu_980_p4}}}, {2'd0}}}, {tmp_42_fu_990_p4}}}, {2'd0}}}, {tmp_43_fu_1000_p4}}}, {2'd0}}}, {tmp_44_fu_1010_p4}}}, {2'd0}}}, {tmp_45_fu_1020_p4}}}, {2'd0}}}, {tmp_46_fu_1030_p4}}}, {2'd0}}}, {tmp_47_fu_1040_p4}}}, {2'd0}}}, {trunc_ln1543_1_fu_890_p4}};

assign trunc_ln232_5_cast_fu_1448_p4 = {{add_ln232_1_fu_1192_p2[55:4]}};

assign trunc_ln232_6_cast_fu_1470_p4 = {{add_ln232_1_fu_1192_p2[39:4]}};

assign trunc_ln4_fu_1747_p3 = {{1'd0}, {tmp_60_reg_1966}};

assign trunc_ln886_1_fu_1834_p4 = {{x_V_3_fu_1804_p2[22:16]}};

assign trunc_ln886_2_fu_1850_p4 = {{x_V_4_fu_1844_p2[38:32]}};

assign trunc_ln886_3_fu_1781_p11 = {{{{{{{{{{{{{{{{{{1'd0}, {tmp_56_reg_1942}}}, {4'd0}}}, {tmp_57_reg_1948}}}, {4'd0}}}, {tmp_58_reg_1954}}}, {4'd0}}}, {tmp_59_reg_1960}}}, {4'd0}}}, {tmp_60_reg_1966}};

assign trunc_ln886_fu_1666_p1 = add_ln16_1_fu_1486_p2[3:0];

assign x_V_3_fu_1804_p2 = (zext_ln886_fu_1739_p1 + zext_ln1715_1_fu_1712_p1);

assign x_V_4_fu_1844_p2 = (zext_ln1715_2_fu_1830_p1 + zext_ln16_2_fu_1816_p1);

assign x_V_5_fu_596_p2 = (ret_V_13_fu_200_p2 - zext_ln1543_fu_592_p1);

assign x_V_fu_1198_p2 = (zext_ln1543_2_fu_1180_p1 + zext_ln1543_1_fu_886_p1);

assign zext_ln1543_1_fu_886_p1 = ret_V_11_fu_756_p32;

assign zext_ln1543_2_fu_1180_p1 = ret_V_12_fu_1050_p32;

assign zext_ln1543_3_fu_1866_p1 = add_ln1543_fu_1860_p2;

assign zext_ln1543_fu_592_p1 = ret_V_fu_462_p64;

assign zext_ln16_1_fu_1320_p1 = trunc_ln16_2_fu_1264_p27;

assign zext_ln16_2_fu_1816_p1 = add_ln16_2_fu_1810_p2;

assign zext_ln16_fu_1260_p1 = trunc_ln16_1_fu_1204_p27;

assign zext_ln1715_1_fu_1712_p1 = and_ln_fu_1687_p15;

assign zext_ln1715_2_fu_1830_p1 = tmp_149_fu_1820_p4;

assign zext_ln1715_fu_1340_p1 = trunc_ln1715_2_fu_1330_p4;

assign zext_ln232_1_fu_1673_p1 = trunc_ln1543_1_reg_1887;

assign zext_ln232_2_fu_1184_p1 = ret_V_11_cast_fu_822_p31;

assign zext_ln232_3_fu_1188_p1 = ret_V_12_cast_fu_1116_p31;

assign zext_ln232_4_fu_1394_p1 = trunc_ln232_3_fu_1354_p19;

assign zext_ln232_5_fu_1438_p1 = trunc_ln232_4_fu_1398_p19;

assign zext_ln232_fu_1670_p1 = trunc_ln1543_reg_1882;

assign zext_ln886_1_fu_1743_p1 = add_ln232_3_fu_1681_p2;

assign zext_ln886_2_fu_1754_p1 = trunc_ln4_fu_1747_p3;

assign zext_ln886_3_fu_1777_p1 = and_ln1_fu_1758_p11;

assign zext_ln886_4_fu_1800_p1 = trunc_ln886_3_fu_1781_p11;

assign zext_ln886_fu_1739_p1 = trunc_ln1715_3_fu_1716_p14;

endmodule //FracNet_T_compute_engine_64
