// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FracNet_T_matmul_Pipeline_VITIS_LOOP_284_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lhs_reload,
        lhs_2_reload,
        lhs_4_reload,
        lhs_6_reload,
        lhs_8_reload,
        lhs_10_reload,
        lhs_12_reload,
        lhs_14_reload,
        lhs_16_reload,
        lhs_18_reload,
        outputs_address0,
        outputs_ce0,
        outputs_we0,
        outputs_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] lhs_reload;
input  [15:0] lhs_2_reload;
input  [15:0] lhs_4_reload;
input  [15:0] lhs_6_reload;
input  [15:0] lhs_8_reload;
input  [15:0] lhs_10_reload;
input  [15:0] lhs_12_reload;
input  [15:0] lhs_14_reload;
input  [15:0] lhs_16_reload;
input  [15:0] lhs_18_reload;
output  [3:0] outputs_address0;
output   outputs_ce0;
output   outputs_we0;
output  [30:0] outputs_d0;

reg ap_idle;
reg outputs_ce0;
reg outputs_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln284_fu_141_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln284_fu_153_p1;
reg   [3:0] coo_fu_56;
wire   [3:0] add_ln284_fu_147_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_coo_1;
wire   [15:0] tmp_s_fu_158_p12;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

FracNet_T_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_104_16_1_1_U2726(
    .din0(lhs_reload),
    .din1(lhs_2_reload),
    .din2(lhs_4_reload),
    .din3(lhs_6_reload),
    .din4(lhs_8_reload),
    .din5(lhs_10_reload),
    .din6(lhs_12_reload),
    .din7(lhs_14_reload),
    .din8(lhs_16_reload),
    .din9(lhs_18_reload),
    .din10(ap_sig_allocacmp_coo_1),
    .dout(tmp_s_fu_158_p12)
);

FracNet_T_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln284_fu_141_p2 == 1'd0)) begin
            coo_fu_56 <= add_ln284_fu_147_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            coo_fu_56 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln284_fu_141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_coo_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_coo_1 = coo_fu_56;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outputs_ce0 = 1'b1;
    end else begin
        outputs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln284_fu_141_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outputs_we0 = 1'b1;
    end else begin
        outputs_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln284_fu_147_p2 = (ap_sig_allocacmp_coo_1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln284_fu_141_p2 = ((ap_sig_allocacmp_coo_1 == 4'd10) ? 1'b1 : 1'b0);

assign outputs_address0 = zext_ln284_fu_153_p1;

assign outputs_d0 = {{tmp_s_fu_158_p12}, {15'd0}};

assign zext_ln284_fu_153_p1 = ap_sig_allocacmp_coo_1;

endmodule //FracNet_T_matmul_Pipeline_VITIS_LOOP_284_5
