// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FracNet_T_quant_and_pack (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        prior_outputs_0_0_address0,
        prior_outputs_0_0_ce0,
        prior_outputs_0_0_q0,
        prior_outputs_0_1_address0,
        prior_outputs_0_1_ce0,
        prior_outputs_0_1_q0,
        prior_outputs_0_2_address0,
        prior_outputs_0_2_ce0,
        prior_outputs_0_2_q0,
        prior_outputs_0_3_address0,
        prior_outputs_0_3_ce0,
        prior_outputs_0_3_q0,
        prior_outputs_0_4_address0,
        prior_outputs_0_4_ce0,
        prior_outputs_0_4_q0,
        prior_outputs_0_5_address0,
        prior_outputs_0_5_ce0,
        prior_outputs_0_5_q0,
        prior_outputs_0_6_address0,
        prior_outputs_0_6_ce0,
        prior_outputs_0_6_q0,
        prior_outputs_0_7_address0,
        prior_outputs_0_7_ce0,
        prior_outputs_0_7_q0,
        prior_outputs_0_8_address0,
        prior_outputs_0_8_ce0,
        prior_outputs_0_8_q0,
        prior_outputs_0_9_address0,
        prior_outputs_0_9_ce0,
        prior_outputs_0_9_q0,
        prior_outputs_0_10_address0,
        prior_outputs_0_10_ce0,
        prior_outputs_0_10_q0,
        prior_outputs_0_11_address0,
        prior_outputs_0_11_ce0,
        prior_outputs_0_11_q0,
        prior_outputs_0_12_address0,
        prior_outputs_0_12_ce0,
        prior_outputs_0_12_q0,
        prior_outputs_0_13_address0,
        prior_outputs_0_13_ce0,
        prior_outputs_0_13_q0,
        prior_outputs_0_14_address0,
        prior_outputs_0_14_ce0,
        prior_outputs_0_14_q0,
        prior_outputs_0_15_address0,
        prior_outputs_0_15_ce0,
        prior_outputs_0_15_q0,
        prior_outputs_1_0_address0,
        prior_outputs_1_0_ce0,
        prior_outputs_1_0_q0,
        prior_outputs_1_1_address0,
        prior_outputs_1_1_ce0,
        prior_outputs_1_1_q0,
        prior_outputs_1_2_address0,
        prior_outputs_1_2_ce0,
        prior_outputs_1_2_q0,
        prior_outputs_1_3_address0,
        prior_outputs_1_3_ce0,
        prior_outputs_1_3_q0,
        prior_outputs_1_4_address0,
        prior_outputs_1_4_ce0,
        prior_outputs_1_4_q0,
        prior_outputs_1_5_address0,
        prior_outputs_1_5_ce0,
        prior_outputs_1_5_q0,
        prior_outputs_1_6_address0,
        prior_outputs_1_6_ce0,
        prior_outputs_1_6_q0,
        prior_outputs_1_7_address0,
        prior_outputs_1_7_ce0,
        prior_outputs_1_7_q0,
        prior_outputs_1_8_address0,
        prior_outputs_1_8_ce0,
        prior_outputs_1_8_q0,
        prior_outputs_1_9_address0,
        prior_outputs_1_9_ce0,
        prior_outputs_1_9_q0,
        prior_outputs_1_10_address0,
        prior_outputs_1_10_ce0,
        prior_outputs_1_10_q0,
        prior_outputs_1_11_address0,
        prior_outputs_1_11_ce0,
        prior_outputs_1_11_q0,
        prior_outputs_1_12_address0,
        prior_outputs_1_12_ce0,
        prior_outputs_1_12_q0,
        prior_outputs_1_13_address0,
        prior_outputs_1_13_ce0,
        prior_outputs_1_13_q0,
        prior_outputs_1_14_address0,
        prior_outputs_1_14_ce0,
        prior_outputs_1_14_q0,
        prior_outputs_1_15_address0,
        prior_outputs_1_15_ce0,
        prior_outputs_1_15_q0,
        prior_outputs_2_0_address0,
        prior_outputs_2_0_ce0,
        prior_outputs_2_0_q0,
        prior_outputs_2_1_address0,
        prior_outputs_2_1_ce0,
        prior_outputs_2_1_q0,
        prior_outputs_2_2_address0,
        prior_outputs_2_2_ce0,
        prior_outputs_2_2_q0,
        prior_outputs_2_3_address0,
        prior_outputs_2_3_ce0,
        prior_outputs_2_3_q0,
        prior_outputs_2_4_address0,
        prior_outputs_2_4_ce0,
        prior_outputs_2_4_q0,
        prior_outputs_2_5_address0,
        prior_outputs_2_5_ce0,
        prior_outputs_2_5_q0,
        prior_outputs_2_6_address0,
        prior_outputs_2_6_ce0,
        prior_outputs_2_6_q0,
        prior_outputs_2_7_address0,
        prior_outputs_2_7_ce0,
        prior_outputs_2_7_q0,
        prior_outputs_2_8_address0,
        prior_outputs_2_8_ce0,
        prior_outputs_2_8_q0,
        prior_outputs_2_9_address0,
        prior_outputs_2_9_ce0,
        prior_outputs_2_9_q0,
        prior_outputs_2_10_address0,
        prior_outputs_2_10_ce0,
        prior_outputs_2_10_q0,
        prior_outputs_2_11_address0,
        prior_outputs_2_11_ce0,
        prior_outputs_2_11_q0,
        prior_outputs_2_12_address0,
        prior_outputs_2_12_ce0,
        prior_outputs_2_12_q0,
        prior_outputs_2_13_address0,
        prior_outputs_2_13_ce0,
        prior_outputs_2_13_q0,
        prior_outputs_2_14_address0,
        prior_outputs_2_14_ce0,
        prior_outputs_2_14_q0,
        prior_outputs_2_15_address0,
        prior_outputs_2_15_ce0,
        prior_outputs_2_15_q0,
        prior_outputs_3_0_address0,
        prior_outputs_3_0_ce0,
        prior_outputs_3_0_q0,
        prior_outputs_3_1_address0,
        prior_outputs_3_1_ce0,
        prior_outputs_3_1_q0,
        prior_outputs_3_2_address0,
        prior_outputs_3_2_ce0,
        prior_outputs_3_2_q0,
        prior_outputs_3_3_address0,
        prior_outputs_3_3_ce0,
        prior_outputs_3_3_q0,
        prior_outputs_3_4_address0,
        prior_outputs_3_4_ce0,
        prior_outputs_3_4_q0,
        prior_outputs_3_5_address0,
        prior_outputs_3_5_ce0,
        prior_outputs_3_5_q0,
        prior_outputs_3_6_address0,
        prior_outputs_3_6_ce0,
        prior_outputs_3_6_q0,
        prior_outputs_3_7_address0,
        prior_outputs_3_7_ce0,
        prior_outputs_3_7_q0,
        prior_outputs_3_8_address0,
        prior_outputs_3_8_ce0,
        prior_outputs_3_8_q0,
        prior_outputs_3_9_address0,
        prior_outputs_3_9_ce0,
        prior_outputs_3_9_q0,
        prior_outputs_3_10_address0,
        prior_outputs_3_10_ce0,
        prior_outputs_3_10_q0,
        prior_outputs_3_11_address0,
        prior_outputs_3_11_ce0,
        prior_outputs_3_11_q0,
        prior_outputs_3_12_address0,
        prior_outputs_3_12_ce0,
        prior_outputs_3_12_q0,
        prior_outputs_3_13_address0,
        prior_outputs_3_13_ce0,
        prior_outputs_3_13_q0,
        prior_outputs_3_14_address0,
        prior_outputs_3_14_ce0,
        prior_outputs_3_14_q0,
        prior_outputs_3_15_address0,
        prior_outputs_3_15_ce0,
        prior_outputs_3_15_q0,
        msb_buffer_0_address0,
        msb_buffer_0_ce0,
        msb_buffer_0_we0,
        msb_buffer_0_d0,
        msb_buffer_0_address1,
        msb_buffer_0_ce1,
        msb_buffer_0_q1,
        msb_buffer_1_address0,
        msb_buffer_1_ce0,
        msb_buffer_1_we0,
        msb_buffer_1_d0,
        msb_buffer_1_address1,
        msb_buffer_1_ce1,
        msb_buffer_1_q1,
        H_fmap,
        in_channels
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] prior_outputs_0_0_address0;
output   prior_outputs_0_0_ce0;
input  [15:0] prior_outputs_0_0_q0;
output  [10:0] prior_outputs_0_1_address0;
output   prior_outputs_0_1_ce0;
input  [15:0] prior_outputs_0_1_q0;
output  [10:0] prior_outputs_0_2_address0;
output   prior_outputs_0_2_ce0;
input  [15:0] prior_outputs_0_2_q0;
output  [10:0] prior_outputs_0_3_address0;
output   prior_outputs_0_3_ce0;
input  [15:0] prior_outputs_0_3_q0;
output  [10:0] prior_outputs_0_4_address0;
output   prior_outputs_0_4_ce0;
input  [15:0] prior_outputs_0_4_q0;
output  [10:0] prior_outputs_0_5_address0;
output   prior_outputs_0_5_ce0;
input  [15:0] prior_outputs_0_5_q0;
output  [10:0] prior_outputs_0_6_address0;
output   prior_outputs_0_6_ce0;
input  [15:0] prior_outputs_0_6_q0;
output  [10:0] prior_outputs_0_7_address0;
output   prior_outputs_0_7_ce0;
input  [15:0] prior_outputs_0_7_q0;
output  [10:0] prior_outputs_0_8_address0;
output   prior_outputs_0_8_ce0;
input  [15:0] prior_outputs_0_8_q0;
output  [10:0] prior_outputs_0_9_address0;
output   prior_outputs_0_9_ce0;
input  [15:0] prior_outputs_0_9_q0;
output  [10:0] prior_outputs_0_10_address0;
output   prior_outputs_0_10_ce0;
input  [15:0] prior_outputs_0_10_q0;
output  [10:0] prior_outputs_0_11_address0;
output   prior_outputs_0_11_ce0;
input  [15:0] prior_outputs_0_11_q0;
output  [10:0] prior_outputs_0_12_address0;
output   prior_outputs_0_12_ce0;
input  [15:0] prior_outputs_0_12_q0;
output  [10:0] prior_outputs_0_13_address0;
output   prior_outputs_0_13_ce0;
input  [15:0] prior_outputs_0_13_q0;
output  [10:0] prior_outputs_0_14_address0;
output   prior_outputs_0_14_ce0;
input  [15:0] prior_outputs_0_14_q0;
output  [10:0] prior_outputs_0_15_address0;
output   prior_outputs_0_15_ce0;
input  [15:0] prior_outputs_0_15_q0;
output  [10:0] prior_outputs_1_0_address0;
output   prior_outputs_1_0_ce0;
input  [15:0] prior_outputs_1_0_q0;
output  [10:0] prior_outputs_1_1_address0;
output   prior_outputs_1_1_ce0;
input  [15:0] prior_outputs_1_1_q0;
output  [10:0] prior_outputs_1_2_address0;
output   prior_outputs_1_2_ce0;
input  [15:0] prior_outputs_1_2_q0;
output  [10:0] prior_outputs_1_3_address0;
output   prior_outputs_1_3_ce0;
input  [15:0] prior_outputs_1_3_q0;
output  [10:0] prior_outputs_1_4_address0;
output   prior_outputs_1_4_ce0;
input  [15:0] prior_outputs_1_4_q0;
output  [10:0] prior_outputs_1_5_address0;
output   prior_outputs_1_5_ce0;
input  [15:0] prior_outputs_1_5_q0;
output  [10:0] prior_outputs_1_6_address0;
output   prior_outputs_1_6_ce0;
input  [15:0] prior_outputs_1_6_q0;
output  [10:0] prior_outputs_1_7_address0;
output   prior_outputs_1_7_ce0;
input  [15:0] prior_outputs_1_7_q0;
output  [10:0] prior_outputs_1_8_address0;
output   prior_outputs_1_8_ce0;
input  [15:0] prior_outputs_1_8_q0;
output  [10:0] prior_outputs_1_9_address0;
output   prior_outputs_1_9_ce0;
input  [15:0] prior_outputs_1_9_q0;
output  [10:0] prior_outputs_1_10_address0;
output   prior_outputs_1_10_ce0;
input  [15:0] prior_outputs_1_10_q0;
output  [10:0] prior_outputs_1_11_address0;
output   prior_outputs_1_11_ce0;
input  [15:0] prior_outputs_1_11_q0;
output  [10:0] prior_outputs_1_12_address0;
output   prior_outputs_1_12_ce0;
input  [15:0] prior_outputs_1_12_q0;
output  [10:0] prior_outputs_1_13_address0;
output   prior_outputs_1_13_ce0;
input  [15:0] prior_outputs_1_13_q0;
output  [10:0] prior_outputs_1_14_address0;
output   prior_outputs_1_14_ce0;
input  [15:0] prior_outputs_1_14_q0;
output  [10:0] prior_outputs_1_15_address0;
output   prior_outputs_1_15_ce0;
input  [15:0] prior_outputs_1_15_q0;
output  [10:0] prior_outputs_2_0_address0;
output   prior_outputs_2_0_ce0;
input  [15:0] prior_outputs_2_0_q0;
output  [10:0] prior_outputs_2_1_address0;
output   prior_outputs_2_1_ce0;
input  [15:0] prior_outputs_2_1_q0;
output  [10:0] prior_outputs_2_2_address0;
output   prior_outputs_2_2_ce0;
input  [15:0] prior_outputs_2_2_q0;
output  [10:0] prior_outputs_2_3_address0;
output   prior_outputs_2_3_ce0;
input  [15:0] prior_outputs_2_3_q0;
output  [10:0] prior_outputs_2_4_address0;
output   prior_outputs_2_4_ce0;
input  [15:0] prior_outputs_2_4_q0;
output  [10:0] prior_outputs_2_5_address0;
output   prior_outputs_2_5_ce0;
input  [15:0] prior_outputs_2_5_q0;
output  [10:0] prior_outputs_2_6_address0;
output   prior_outputs_2_6_ce0;
input  [15:0] prior_outputs_2_6_q0;
output  [10:0] prior_outputs_2_7_address0;
output   prior_outputs_2_7_ce0;
input  [15:0] prior_outputs_2_7_q0;
output  [10:0] prior_outputs_2_8_address0;
output   prior_outputs_2_8_ce0;
input  [15:0] prior_outputs_2_8_q0;
output  [10:0] prior_outputs_2_9_address0;
output   prior_outputs_2_9_ce0;
input  [15:0] prior_outputs_2_9_q0;
output  [10:0] prior_outputs_2_10_address0;
output   prior_outputs_2_10_ce0;
input  [15:0] prior_outputs_2_10_q0;
output  [10:0] prior_outputs_2_11_address0;
output   prior_outputs_2_11_ce0;
input  [15:0] prior_outputs_2_11_q0;
output  [10:0] prior_outputs_2_12_address0;
output   prior_outputs_2_12_ce0;
input  [15:0] prior_outputs_2_12_q0;
output  [10:0] prior_outputs_2_13_address0;
output   prior_outputs_2_13_ce0;
input  [15:0] prior_outputs_2_13_q0;
output  [10:0] prior_outputs_2_14_address0;
output   prior_outputs_2_14_ce0;
input  [15:0] prior_outputs_2_14_q0;
output  [10:0] prior_outputs_2_15_address0;
output   prior_outputs_2_15_ce0;
input  [15:0] prior_outputs_2_15_q0;
output  [10:0] prior_outputs_3_0_address0;
output   prior_outputs_3_0_ce0;
input  [15:0] prior_outputs_3_0_q0;
output  [10:0] prior_outputs_3_1_address0;
output   prior_outputs_3_1_ce0;
input  [15:0] prior_outputs_3_1_q0;
output  [10:0] prior_outputs_3_2_address0;
output   prior_outputs_3_2_ce0;
input  [15:0] prior_outputs_3_2_q0;
output  [10:0] prior_outputs_3_3_address0;
output   prior_outputs_3_3_ce0;
input  [15:0] prior_outputs_3_3_q0;
output  [10:0] prior_outputs_3_4_address0;
output   prior_outputs_3_4_ce0;
input  [15:0] prior_outputs_3_4_q0;
output  [10:0] prior_outputs_3_5_address0;
output   prior_outputs_3_5_ce0;
input  [15:0] prior_outputs_3_5_q0;
output  [10:0] prior_outputs_3_6_address0;
output   prior_outputs_3_6_ce0;
input  [15:0] prior_outputs_3_6_q0;
output  [10:0] prior_outputs_3_7_address0;
output   prior_outputs_3_7_ce0;
input  [15:0] prior_outputs_3_7_q0;
output  [10:0] prior_outputs_3_8_address0;
output   prior_outputs_3_8_ce0;
input  [15:0] prior_outputs_3_8_q0;
output  [10:0] prior_outputs_3_9_address0;
output   prior_outputs_3_9_ce0;
input  [15:0] prior_outputs_3_9_q0;
output  [10:0] prior_outputs_3_10_address0;
output   prior_outputs_3_10_ce0;
input  [15:0] prior_outputs_3_10_q0;
output  [10:0] prior_outputs_3_11_address0;
output   prior_outputs_3_11_ce0;
input  [15:0] prior_outputs_3_11_q0;
output  [10:0] prior_outputs_3_12_address0;
output   prior_outputs_3_12_ce0;
input  [15:0] prior_outputs_3_12_q0;
output  [10:0] prior_outputs_3_13_address0;
output   prior_outputs_3_13_ce0;
input  [15:0] prior_outputs_3_13_q0;
output  [10:0] prior_outputs_3_14_address0;
output   prior_outputs_3_14_ce0;
input  [15:0] prior_outputs_3_14_q0;
output  [10:0] prior_outputs_3_15_address0;
output   prior_outputs_3_15_ce0;
input  [15:0] prior_outputs_3_15_q0;
output  [10:0] msb_buffer_0_address0;
output   msb_buffer_0_ce0;
output   msb_buffer_0_we0;
output  [63:0] msb_buffer_0_d0;
output  [10:0] msb_buffer_0_address1;
output   msb_buffer_0_ce1;
input  [63:0] msb_buffer_0_q1;
output  [10:0] msb_buffer_1_address0;
output   msb_buffer_1_ce0;
output   msb_buffer_1_we0;
output  [63:0] msb_buffer_1_d0;
output  [10:0] msb_buffer_1_address1;
output   msb_buffer_1_ce1;
input  [63:0] msb_buffer_1_q1;
input  [5:0] H_fmap;
input  [6:0] in_channels;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] bound_fu_307_p2;
reg   [11:0] bound_reg_340;
wire   [13:0] tmp_15_fu_314_p3;
reg   [13:0] tmp_15_reg_345;
wire   [0:0] icmp_ln39_fu_323_p2;
reg   [0:0] icmp_ln39_reg_350;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_idle;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_ready;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_ce0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_we0;
wire   [63:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_d0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address1;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce1;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce0;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_we0;
wire   [63:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_d0;
wire   [10:0] grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address1;
wire    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce1;
reg    grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [5:0] bound_fu_307_p0;
wire   [11:0] cast_fu_303_p1;
wire   [5:0] bound_fu_307_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg = 1'b0;
end

FracNet_T_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2 grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start),
    .ap_done(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done),
    .ap_idle(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_idle),
    .ap_ready(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_ready),
    .zext_ln37(in_channels),
    .bound4(tmp_15_reg_345),
    .bound(bound_reg_340),
    .H_fmap(H_fmap),
    .icmp_ln39_1(icmp_ln39_reg_350),
    .prior_outputs_0_0_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_address0),
    .prior_outputs_0_0_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_ce0),
    .prior_outputs_0_0_q0(prior_outputs_0_0_q0),
    .prior_outputs_0_1_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_address0),
    .prior_outputs_0_1_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_ce0),
    .prior_outputs_0_1_q0(prior_outputs_0_1_q0),
    .prior_outputs_0_2_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_address0),
    .prior_outputs_0_2_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_ce0),
    .prior_outputs_0_2_q0(prior_outputs_0_2_q0),
    .prior_outputs_0_3_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_address0),
    .prior_outputs_0_3_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_ce0),
    .prior_outputs_0_3_q0(prior_outputs_0_3_q0),
    .prior_outputs_0_4_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_address0),
    .prior_outputs_0_4_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_ce0),
    .prior_outputs_0_4_q0(prior_outputs_0_4_q0),
    .prior_outputs_0_5_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_address0),
    .prior_outputs_0_5_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_ce0),
    .prior_outputs_0_5_q0(prior_outputs_0_5_q0),
    .prior_outputs_0_6_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_address0),
    .prior_outputs_0_6_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_ce0),
    .prior_outputs_0_6_q0(prior_outputs_0_6_q0),
    .prior_outputs_0_7_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_address0),
    .prior_outputs_0_7_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_ce0),
    .prior_outputs_0_7_q0(prior_outputs_0_7_q0),
    .prior_outputs_0_8_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_address0),
    .prior_outputs_0_8_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_ce0),
    .prior_outputs_0_8_q0(prior_outputs_0_8_q0),
    .prior_outputs_0_9_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_address0),
    .prior_outputs_0_9_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_ce0),
    .prior_outputs_0_9_q0(prior_outputs_0_9_q0),
    .prior_outputs_0_10_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_address0),
    .prior_outputs_0_10_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_ce0),
    .prior_outputs_0_10_q0(prior_outputs_0_10_q0),
    .prior_outputs_0_11_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_address0),
    .prior_outputs_0_11_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_ce0),
    .prior_outputs_0_11_q0(prior_outputs_0_11_q0),
    .prior_outputs_0_12_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_address0),
    .prior_outputs_0_12_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_ce0),
    .prior_outputs_0_12_q0(prior_outputs_0_12_q0),
    .prior_outputs_0_13_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_address0),
    .prior_outputs_0_13_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_ce0),
    .prior_outputs_0_13_q0(prior_outputs_0_13_q0),
    .prior_outputs_0_14_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_address0),
    .prior_outputs_0_14_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_ce0),
    .prior_outputs_0_14_q0(prior_outputs_0_14_q0),
    .prior_outputs_0_15_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_address0),
    .prior_outputs_0_15_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_ce0),
    .prior_outputs_0_15_q0(prior_outputs_0_15_q0),
    .prior_outputs_1_0_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_address0),
    .prior_outputs_1_0_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_ce0),
    .prior_outputs_1_0_q0(prior_outputs_1_0_q0),
    .prior_outputs_1_1_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_address0),
    .prior_outputs_1_1_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_ce0),
    .prior_outputs_1_1_q0(prior_outputs_1_1_q0),
    .prior_outputs_1_2_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_address0),
    .prior_outputs_1_2_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_ce0),
    .prior_outputs_1_2_q0(prior_outputs_1_2_q0),
    .prior_outputs_1_3_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_address0),
    .prior_outputs_1_3_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_ce0),
    .prior_outputs_1_3_q0(prior_outputs_1_3_q0),
    .prior_outputs_1_4_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_address0),
    .prior_outputs_1_4_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_ce0),
    .prior_outputs_1_4_q0(prior_outputs_1_4_q0),
    .prior_outputs_1_5_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_address0),
    .prior_outputs_1_5_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_ce0),
    .prior_outputs_1_5_q0(prior_outputs_1_5_q0),
    .prior_outputs_1_6_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_address0),
    .prior_outputs_1_6_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_ce0),
    .prior_outputs_1_6_q0(prior_outputs_1_6_q0),
    .prior_outputs_1_7_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_address0),
    .prior_outputs_1_7_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_ce0),
    .prior_outputs_1_7_q0(prior_outputs_1_7_q0),
    .prior_outputs_1_8_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_address0),
    .prior_outputs_1_8_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_ce0),
    .prior_outputs_1_8_q0(prior_outputs_1_8_q0),
    .prior_outputs_1_9_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_address0),
    .prior_outputs_1_9_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_ce0),
    .prior_outputs_1_9_q0(prior_outputs_1_9_q0),
    .prior_outputs_1_10_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_address0),
    .prior_outputs_1_10_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_ce0),
    .prior_outputs_1_10_q0(prior_outputs_1_10_q0),
    .prior_outputs_1_11_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_address0),
    .prior_outputs_1_11_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_ce0),
    .prior_outputs_1_11_q0(prior_outputs_1_11_q0),
    .prior_outputs_1_12_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_address0),
    .prior_outputs_1_12_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_ce0),
    .prior_outputs_1_12_q0(prior_outputs_1_12_q0),
    .prior_outputs_1_13_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_address0),
    .prior_outputs_1_13_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_ce0),
    .prior_outputs_1_13_q0(prior_outputs_1_13_q0),
    .prior_outputs_1_14_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_address0),
    .prior_outputs_1_14_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_ce0),
    .prior_outputs_1_14_q0(prior_outputs_1_14_q0),
    .prior_outputs_1_15_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_address0),
    .prior_outputs_1_15_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_ce0),
    .prior_outputs_1_15_q0(prior_outputs_1_15_q0),
    .prior_outputs_2_0_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_address0),
    .prior_outputs_2_0_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_ce0),
    .prior_outputs_2_0_q0(prior_outputs_2_0_q0),
    .prior_outputs_2_1_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_address0),
    .prior_outputs_2_1_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_ce0),
    .prior_outputs_2_1_q0(prior_outputs_2_1_q0),
    .prior_outputs_2_2_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_address0),
    .prior_outputs_2_2_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_ce0),
    .prior_outputs_2_2_q0(prior_outputs_2_2_q0),
    .prior_outputs_2_3_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_address0),
    .prior_outputs_2_3_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_ce0),
    .prior_outputs_2_3_q0(prior_outputs_2_3_q0),
    .prior_outputs_2_4_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_address0),
    .prior_outputs_2_4_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_ce0),
    .prior_outputs_2_4_q0(prior_outputs_2_4_q0),
    .prior_outputs_2_5_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_address0),
    .prior_outputs_2_5_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_ce0),
    .prior_outputs_2_5_q0(prior_outputs_2_5_q0),
    .prior_outputs_2_6_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_address0),
    .prior_outputs_2_6_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_ce0),
    .prior_outputs_2_6_q0(prior_outputs_2_6_q0),
    .prior_outputs_2_7_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_address0),
    .prior_outputs_2_7_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_ce0),
    .prior_outputs_2_7_q0(prior_outputs_2_7_q0),
    .prior_outputs_2_8_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_address0),
    .prior_outputs_2_8_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_ce0),
    .prior_outputs_2_8_q0(prior_outputs_2_8_q0),
    .prior_outputs_2_9_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_address0),
    .prior_outputs_2_9_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_ce0),
    .prior_outputs_2_9_q0(prior_outputs_2_9_q0),
    .prior_outputs_2_10_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_address0),
    .prior_outputs_2_10_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_ce0),
    .prior_outputs_2_10_q0(prior_outputs_2_10_q0),
    .prior_outputs_2_11_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_address0),
    .prior_outputs_2_11_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_ce0),
    .prior_outputs_2_11_q0(prior_outputs_2_11_q0),
    .prior_outputs_2_12_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_address0),
    .prior_outputs_2_12_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_ce0),
    .prior_outputs_2_12_q0(prior_outputs_2_12_q0),
    .prior_outputs_2_13_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_address0),
    .prior_outputs_2_13_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_ce0),
    .prior_outputs_2_13_q0(prior_outputs_2_13_q0),
    .prior_outputs_2_14_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_address0),
    .prior_outputs_2_14_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_ce0),
    .prior_outputs_2_14_q0(prior_outputs_2_14_q0),
    .prior_outputs_2_15_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_address0),
    .prior_outputs_2_15_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_ce0),
    .prior_outputs_2_15_q0(prior_outputs_2_15_q0),
    .prior_outputs_3_0_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_address0),
    .prior_outputs_3_0_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_ce0),
    .prior_outputs_3_0_q0(prior_outputs_3_0_q0),
    .prior_outputs_3_1_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_address0),
    .prior_outputs_3_1_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_ce0),
    .prior_outputs_3_1_q0(prior_outputs_3_1_q0),
    .prior_outputs_3_2_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_address0),
    .prior_outputs_3_2_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_ce0),
    .prior_outputs_3_2_q0(prior_outputs_3_2_q0),
    .prior_outputs_3_3_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_address0),
    .prior_outputs_3_3_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_ce0),
    .prior_outputs_3_3_q0(prior_outputs_3_3_q0),
    .prior_outputs_3_4_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_address0),
    .prior_outputs_3_4_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_ce0),
    .prior_outputs_3_4_q0(prior_outputs_3_4_q0),
    .prior_outputs_3_5_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_address0),
    .prior_outputs_3_5_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_ce0),
    .prior_outputs_3_5_q0(prior_outputs_3_5_q0),
    .prior_outputs_3_6_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_address0),
    .prior_outputs_3_6_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_ce0),
    .prior_outputs_3_6_q0(prior_outputs_3_6_q0),
    .prior_outputs_3_7_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_address0),
    .prior_outputs_3_7_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_ce0),
    .prior_outputs_3_7_q0(prior_outputs_3_7_q0),
    .prior_outputs_3_8_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_address0),
    .prior_outputs_3_8_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_ce0),
    .prior_outputs_3_8_q0(prior_outputs_3_8_q0),
    .prior_outputs_3_9_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_address0),
    .prior_outputs_3_9_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_ce0),
    .prior_outputs_3_9_q0(prior_outputs_3_9_q0),
    .prior_outputs_3_10_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_address0),
    .prior_outputs_3_10_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_ce0),
    .prior_outputs_3_10_q0(prior_outputs_3_10_q0),
    .prior_outputs_3_11_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_address0),
    .prior_outputs_3_11_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_ce0),
    .prior_outputs_3_11_q0(prior_outputs_3_11_q0),
    .prior_outputs_3_12_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_address0),
    .prior_outputs_3_12_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_ce0),
    .prior_outputs_3_12_q0(prior_outputs_3_12_q0),
    .prior_outputs_3_13_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_address0),
    .prior_outputs_3_13_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_ce0),
    .prior_outputs_3_13_q0(prior_outputs_3_13_q0),
    .prior_outputs_3_14_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_address0),
    .prior_outputs_3_14_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_ce0),
    .prior_outputs_3_14_q0(prior_outputs_3_14_q0),
    .prior_outputs_3_15_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_address0),
    .prior_outputs_3_15_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_ce0),
    .prior_outputs_3_15_q0(prior_outputs_3_15_q0),
    .msb_buffer_0_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address0),
    .msb_buffer_0_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce0),
    .msb_buffer_0_we0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_we0),
    .msb_buffer_0_d0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_d0),
    .msb_buffer_0_address1(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address1),
    .msb_buffer_0_ce1(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce1),
    .msb_buffer_0_q1(msb_buffer_0_q1),
    .msb_buffer_1_address0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address0),
    .msb_buffer_1_ce0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce0),
    .msb_buffer_1_we0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_we0),
    .msb_buffer_1_d0(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_d0),
    .msb_buffer_1_address1(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address1),
    .msb_buffer_1_ce1(grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce1),
    .msb_buffer_1_q1(msb_buffer_1_q1)
);

FracNet_T_mul_6ns_6ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6ns_6ns_12_1_1_U446(
    .din0(bound_fu_307_p0),
    .din1(bound_fu_307_p1),
    .dout(bound_fu_307_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_ready == 1'b1)) begin
            grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_reg_340 <= bound_fu_307_p2;
        icmp_ln39_reg_350 <= icmp_ln39_fu_323_p2;
        tmp_15_reg_345[13 : 2] <= tmp_15_fu_314_p3[13 : 2];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign bound_fu_307_p0 = cast_fu_303_p1;

assign bound_fu_307_p1 = cast_fu_303_p1;

assign cast_fu_303_p1 = H_fmap;

assign grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_ap_start_reg;

assign icmp_ln39_fu_323_p2 = ((H_fmap == 6'd0) ? 1'b1 : 1'b0);

assign msb_buffer_0_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address0;

assign msb_buffer_0_address1 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_address1;

assign msb_buffer_0_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce0;

assign msb_buffer_0_ce1 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_ce1;

assign msb_buffer_0_d0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_d0;

assign msb_buffer_0_we0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_0_we0;

assign msb_buffer_1_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address0;

assign msb_buffer_1_address1 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_address1;

assign msb_buffer_1_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce0;

assign msb_buffer_1_ce1 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_ce1;

assign msb_buffer_1_d0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_d0;

assign msb_buffer_1_we0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_msb_buffer_1_we0;

assign prior_outputs_0_0_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_address0;

assign prior_outputs_0_0_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_0_ce0;

assign prior_outputs_0_10_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_address0;

assign prior_outputs_0_10_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_10_ce0;

assign prior_outputs_0_11_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_address0;

assign prior_outputs_0_11_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_11_ce0;

assign prior_outputs_0_12_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_address0;

assign prior_outputs_0_12_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_12_ce0;

assign prior_outputs_0_13_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_address0;

assign prior_outputs_0_13_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_13_ce0;

assign prior_outputs_0_14_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_address0;

assign prior_outputs_0_14_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_14_ce0;

assign prior_outputs_0_15_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_address0;

assign prior_outputs_0_15_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_15_ce0;

assign prior_outputs_0_1_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_address0;

assign prior_outputs_0_1_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_1_ce0;

assign prior_outputs_0_2_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_address0;

assign prior_outputs_0_2_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_2_ce0;

assign prior_outputs_0_3_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_address0;

assign prior_outputs_0_3_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_3_ce0;

assign prior_outputs_0_4_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_address0;

assign prior_outputs_0_4_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_4_ce0;

assign prior_outputs_0_5_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_address0;

assign prior_outputs_0_5_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_5_ce0;

assign prior_outputs_0_6_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_address0;

assign prior_outputs_0_6_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_6_ce0;

assign prior_outputs_0_7_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_address0;

assign prior_outputs_0_7_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_7_ce0;

assign prior_outputs_0_8_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_address0;

assign prior_outputs_0_8_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_8_ce0;

assign prior_outputs_0_9_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_address0;

assign prior_outputs_0_9_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_0_9_ce0;

assign prior_outputs_1_0_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_address0;

assign prior_outputs_1_0_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_0_ce0;

assign prior_outputs_1_10_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_address0;

assign prior_outputs_1_10_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_10_ce0;

assign prior_outputs_1_11_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_address0;

assign prior_outputs_1_11_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_11_ce0;

assign prior_outputs_1_12_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_address0;

assign prior_outputs_1_12_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_12_ce0;

assign prior_outputs_1_13_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_address0;

assign prior_outputs_1_13_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_13_ce0;

assign prior_outputs_1_14_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_address0;

assign prior_outputs_1_14_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_14_ce0;

assign prior_outputs_1_15_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_address0;

assign prior_outputs_1_15_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_15_ce0;

assign prior_outputs_1_1_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_address0;

assign prior_outputs_1_1_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_1_ce0;

assign prior_outputs_1_2_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_address0;

assign prior_outputs_1_2_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_2_ce0;

assign prior_outputs_1_3_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_address0;

assign prior_outputs_1_3_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_3_ce0;

assign prior_outputs_1_4_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_address0;

assign prior_outputs_1_4_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_4_ce0;

assign prior_outputs_1_5_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_address0;

assign prior_outputs_1_5_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_5_ce0;

assign prior_outputs_1_6_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_address0;

assign prior_outputs_1_6_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_6_ce0;

assign prior_outputs_1_7_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_address0;

assign prior_outputs_1_7_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_7_ce0;

assign prior_outputs_1_8_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_address0;

assign prior_outputs_1_8_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_8_ce0;

assign prior_outputs_1_9_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_address0;

assign prior_outputs_1_9_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_1_9_ce0;

assign prior_outputs_2_0_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_address0;

assign prior_outputs_2_0_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_0_ce0;

assign prior_outputs_2_10_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_address0;

assign prior_outputs_2_10_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_10_ce0;

assign prior_outputs_2_11_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_address0;

assign prior_outputs_2_11_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_11_ce0;

assign prior_outputs_2_12_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_address0;

assign prior_outputs_2_12_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_12_ce0;

assign prior_outputs_2_13_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_address0;

assign prior_outputs_2_13_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_13_ce0;

assign prior_outputs_2_14_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_address0;

assign prior_outputs_2_14_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_14_ce0;

assign prior_outputs_2_15_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_address0;

assign prior_outputs_2_15_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_15_ce0;

assign prior_outputs_2_1_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_address0;

assign prior_outputs_2_1_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_1_ce0;

assign prior_outputs_2_2_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_address0;

assign prior_outputs_2_2_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_2_ce0;

assign prior_outputs_2_3_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_address0;

assign prior_outputs_2_3_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_3_ce0;

assign prior_outputs_2_4_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_address0;

assign prior_outputs_2_4_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_4_ce0;

assign prior_outputs_2_5_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_address0;

assign prior_outputs_2_5_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_5_ce0;

assign prior_outputs_2_6_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_address0;

assign prior_outputs_2_6_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_6_ce0;

assign prior_outputs_2_7_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_address0;

assign prior_outputs_2_7_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_7_ce0;

assign prior_outputs_2_8_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_address0;

assign prior_outputs_2_8_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_8_ce0;

assign prior_outputs_2_9_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_address0;

assign prior_outputs_2_9_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_2_9_ce0;

assign prior_outputs_3_0_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_address0;

assign prior_outputs_3_0_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_0_ce0;

assign prior_outputs_3_10_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_address0;

assign prior_outputs_3_10_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_10_ce0;

assign prior_outputs_3_11_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_address0;

assign prior_outputs_3_11_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_11_ce0;

assign prior_outputs_3_12_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_address0;

assign prior_outputs_3_12_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_12_ce0;

assign prior_outputs_3_13_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_address0;

assign prior_outputs_3_13_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_13_ce0;

assign prior_outputs_3_14_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_address0;

assign prior_outputs_3_14_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_14_ce0;

assign prior_outputs_3_15_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_address0;

assign prior_outputs_3_15_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_15_ce0;

assign prior_outputs_3_1_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_address0;

assign prior_outputs_3_1_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_1_ce0;

assign prior_outputs_3_2_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_address0;

assign prior_outputs_3_2_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_2_ce0;

assign prior_outputs_3_3_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_address0;

assign prior_outputs_3_3_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_3_ce0;

assign prior_outputs_3_4_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_address0;

assign prior_outputs_3_4_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_4_ce0;

assign prior_outputs_3_5_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_address0;

assign prior_outputs_3_5_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_5_ce0;

assign prior_outputs_3_6_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_address0;

assign prior_outputs_3_6_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_6_ce0;

assign prior_outputs_3_7_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_address0;

assign prior_outputs_3_7_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_7_ce0;

assign prior_outputs_3_8_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_address0;

assign prior_outputs_3_8_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_8_ce0;

assign prior_outputs_3_9_address0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_address0;

assign prior_outputs_3_9_ce0 = grp_quant_and_pack_Pipeline_LOOP_Quant_Pack_VITIS_LOOP_38_1_VITIS_LOOP_39_2_fu_160_prior_outputs_3_9_ce0;

assign tmp_15_fu_314_p3 = {{bound_fu_307_p2}, {2'd0}};

always @ (posedge ap_clk) begin
    tmp_15_reg_345[1:0] <= 2'b00;
end

endmodule //FracNet_T_quant_and_pack
